package com.benxiaopao.provider.dao.map;

import com.benxiaopao.provider.dao.model.Ipaddress;
import com.benxiaopao.provider.dao.model.IpaddressExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface IpaddressMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ipaddress
     *
     * @mbg.generated Sun May 05 00:45:47 CST 2019
     */
    @SelectProvider(type=IpaddressSqlProvider.class, method="countByExample")
    long countByExample(IpaddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ipaddress
     *
     * @mbg.generated Sun May 05 00:45:47 CST 2019
     */
    @DeleteProvider(type=IpaddressSqlProvider.class, method="deleteByExample")
    int deleteByExample(IpaddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ipaddress
     *
     * @mbg.generated Sun May 05 00:45:47 CST 2019
     */
    @Delete({
        "delete from ipaddress",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ipaddress
     *
     * @mbg.generated Sun May 05 00:45:47 CST 2019
     */
    @Insert({
        "insert into ipaddress (id, startip, ",
        "endip, address, detail)",
        "values (#{id,jdbcType=INTEGER}, #{startip,jdbcType=BIGINT}, ",
        "#{endip,jdbcType=BIGINT}, #{address,jdbcType=VARCHAR}, #{detail,jdbcType=VARCHAR})"
    })
    int insert(Ipaddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ipaddress
     *
     * @mbg.generated Sun May 05 00:45:47 CST 2019
     */
    @InsertProvider(type=IpaddressSqlProvider.class, method="insertSelective")
    int insertSelective(Ipaddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ipaddress
     *
     * @mbg.generated Sun May 05 00:45:47 CST 2019
     */
    @SelectProvider(type=IpaddressSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="startip", property="startip", jdbcType=JdbcType.BIGINT),
        @Result(column="endip", property="endip", jdbcType=JdbcType.BIGINT),
        @Result(column="address", property="address", jdbcType=JdbcType.VARCHAR),
        @Result(column="detail", property="detail", jdbcType=JdbcType.VARCHAR)
    })
    List<Ipaddress> selectByExample(IpaddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ipaddress
     *
     * @mbg.generated Sun May 05 00:45:47 CST 2019
     */
    @Select({
        "select",
        "id, startip, endip, address, detail",
        "from ipaddress",
        "where id = #{id,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="id", property="id", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="startip", property="startip", jdbcType=JdbcType.BIGINT),
        @Result(column="endip", property="endip", jdbcType=JdbcType.BIGINT),
        @Result(column="address", property="address", jdbcType=JdbcType.VARCHAR),
        @Result(column="detail", property="detail", jdbcType=JdbcType.VARCHAR)
    })
    Ipaddress selectByPrimaryKey(Integer id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ipaddress
     *
     * @mbg.generated Sun May 05 00:45:47 CST 2019
     */
    @UpdateProvider(type=IpaddressSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") Ipaddress record, @Param("example") IpaddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ipaddress
     *
     * @mbg.generated Sun May 05 00:45:47 CST 2019
     */
    @UpdateProvider(type=IpaddressSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") Ipaddress record, @Param("example") IpaddressExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ipaddress
     *
     * @mbg.generated Sun May 05 00:45:47 CST 2019
     */
    @UpdateProvider(type=IpaddressSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(Ipaddress record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table ipaddress
     *
     * @mbg.generated Sun May 05 00:45:47 CST 2019
     */
    @Update({
        "update ipaddress",
        "set startip = #{startip,jdbcType=BIGINT},",
          "endip = #{endip,jdbcType=BIGINT},",
          "address = #{address,jdbcType=VARCHAR},",
          "detail = #{detail,jdbcType=VARCHAR}",
        "where id = #{id,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(Ipaddress record);

    /**
     * 根据long型的ip地址，获取此ip的地理位置
     * @param ip
     * @return
     * @author liupoyang
     */
    @Select({
            "SELECT B.*",
            "FROM ipaddress A JOIN ipaddress B ON A.id = B.id",
            "WHERE #{ip} BETWEEN A.startip AND A.endip"
    })
    public Ipaddress queryLoacationByIp(@Param("ip") long ip);
}