package com.benxiaopao.provider.dao.map;

import com.benxiaopao.provider.dao.model.MobileAuthen;
import com.benxiaopao.provider.dao.model.MobileAuthenExample.Criteria;
import com.benxiaopao.provider.dao.model.MobileAuthenExample.Criterion;
import com.benxiaopao.provider.dao.model.MobileAuthenExample;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class MobileAuthenSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_authen
     *
     * @mbg.generated Sat Apr 20 10:27:14 CST 2019
     */
    public String countByExample(MobileAuthenExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("mobile_authen");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_authen
     *
     * @mbg.generated Sat Apr 20 10:27:14 CST 2019
     */
    public String deleteByExample(MobileAuthenExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("mobile_authen");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_authen
     *
     * @mbg.generated Sat Apr 20 10:27:14 CST 2019
     */
    public String insertSelective(MobileAuthen record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("mobile_authen");
        
        if (record.getMobileAuthenId() != null) {
            sql.VALUES("mobileAuthenId", "#{mobileAuthenId,jdbcType=BIGINT}");
        }
        
        if (record.getMobile() != null) {
            sql.VALUES("mobile", "#{mobile,jdbcType=VARCHAR}");
        }
        
        if (record.getSendTime() != null) {
            sql.VALUES("sendTime", "#{sendTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getValidCode() != null) {
            sql.VALUES("validCode", "#{validCode,jdbcType=VARCHAR}");
        }
        
        if (record.getUserId() != null) {
            sql.VALUES("userId", "#{userId,jdbcType=INTEGER}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_authen
     *
     * @mbg.generated Sat Apr 20 10:27:14 CST 2019
     */
    public String selectByExample(MobileAuthenExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("mobileAuthenId");
        } else {
            sql.SELECT("mobileAuthenId");
        }
        sql.SELECT("mobile");
        sql.SELECT("sendTime");
        sql.SELECT("validCode");
        sql.SELECT("userId");
        sql.FROM("mobile_authen");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_authen
     *
     * @mbg.generated Sat Apr 20 10:27:14 CST 2019
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        MobileAuthen record = (MobileAuthen) parameter.get("record");
        MobileAuthenExample example = (MobileAuthenExample) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("mobile_authen");
        
        if (record.getMobileAuthenId() != null) {
            sql.SET("mobileAuthenId = #{record.mobileAuthenId,jdbcType=BIGINT}");
        }
        
        if (record.getMobile() != null) {
            sql.SET("mobile = #{record.mobile,jdbcType=VARCHAR}");
        }
        
        if (record.getSendTime() != null) {
            sql.SET("sendTime = #{record.sendTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getValidCode() != null) {
            sql.SET("validCode = #{record.validCode,jdbcType=VARCHAR}");
        }
        
        if (record.getUserId() != null) {
            sql.SET("userId = #{record.userId,jdbcType=INTEGER}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_authen
     *
     * @mbg.generated Sat Apr 20 10:27:14 CST 2019
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("mobile_authen");
        
        sql.SET("mobileAuthenId = #{record.mobileAuthenId,jdbcType=BIGINT}");
        sql.SET("mobile = #{record.mobile,jdbcType=VARCHAR}");
        sql.SET("sendTime = #{record.sendTime,jdbcType=TIMESTAMP}");
        sql.SET("validCode = #{record.validCode,jdbcType=VARCHAR}");
        sql.SET("userId = #{record.userId,jdbcType=INTEGER}");
        
        MobileAuthenExample example = (MobileAuthenExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_authen
     *
     * @mbg.generated Sat Apr 20 10:27:14 CST 2019
     */
    public String updateByPrimaryKeySelective(MobileAuthen record) {
        SQL sql = new SQL();
        sql.UPDATE("mobile_authen");
        
        if (record.getMobile() != null) {
            sql.SET("mobile = #{mobile,jdbcType=VARCHAR}");
        }
        
        if (record.getSendTime() != null) {
            sql.SET("sendTime = #{sendTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getValidCode() != null) {
            sql.SET("validCode = #{validCode,jdbcType=VARCHAR}");
        }
        
        if (record.getUserId() != null) {
            sql.SET("userId = #{userId,jdbcType=INTEGER}");
        }
        
        sql.WHERE("mobileAuthenId = #{mobileAuthenId,jdbcType=BIGINT}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table mobile_authen
     *
     * @mbg.generated Sat Apr 20 10:27:14 CST 2019
     */
    protected void applyWhere(SQL sql, MobileAuthenExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}