package com.benxiaopao.provider.dao.map;

import com.benxiaopao.provider.dao.model.OrderItem;
import com.benxiaopao.provider.dao.model.OrderItemExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface OrderItemMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbg.generated Sat Apr 20 10:25:51 CST 2019
     */
    @SelectProvider(type=OrderItemSqlProvider.class, method="countByExample")
    long countByExample(OrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbg.generated Sat Apr 20 10:25:51 CST 2019
     */
    @DeleteProvider(type=OrderItemSqlProvider.class, method="deleteByExample")
    int deleteByExample(OrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbg.generated Sat Apr 20 10:25:51 CST 2019
     */
    @Delete({
        "delete from order_item",
        "where itemId = #{itemId,jdbcType=VARCHAR}"
    })
    int deleteByPrimaryKey(String itemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbg.generated Sat Apr 20 10:25:51 CST 2019
     */
    @Insert({
        "insert into order_item (itemId, orderId, ",
        "productId, productName, ",
        "originPrice, shopPrice, ",
        "productCount, productIcon, ",
        "createTime, updateTime)",
        "values (#{itemId,jdbcType=VARCHAR}, #{orderId,jdbcType=VARCHAR}, ",
        "#{productId,jdbcType=VARCHAR}, #{productName,jdbcType=VARCHAR}, ",
        "#{originPrice,jdbcType=DECIMAL}, #{shopPrice,jdbcType=DECIMAL}, ",
        "#{productCount,jdbcType=INTEGER}, #{productIcon,jdbcType=VARCHAR}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{updateTime,jdbcType=TIMESTAMP})"
    })
    int insert(OrderItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbg.generated Sat Apr 20 10:25:51 CST 2019
     */
    @InsertProvider(type=OrderItemSqlProvider.class, method="insertSelective")
    int insertSelective(OrderItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbg.generated Sat Apr 20 10:25:51 CST 2019
     */
    @SelectProvider(type=OrderItemSqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="itemId", property="itemId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="orderId", property="orderId", jdbcType=JdbcType.VARCHAR),
        @Result(column="productId", property="productId", jdbcType=JdbcType.VARCHAR),
        @Result(column="productName", property="productName", jdbcType=JdbcType.VARCHAR),
        @Result(column="originPrice", property="originPrice", jdbcType=JdbcType.DECIMAL),
        @Result(column="shopPrice", property="shopPrice", jdbcType=JdbcType.DECIMAL),
        @Result(column="productCount", property="productCount", jdbcType=JdbcType.INTEGER),
        @Result(column="productIcon", property="productIcon", jdbcType=JdbcType.VARCHAR),
        @Result(column="createTime", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="updateTime", property="updateTime", jdbcType=JdbcType.TIMESTAMP)
    })
    List<OrderItem> selectByExample(OrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbg.generated Sat Apr 20 10:25:51 CST 2019
     */
    @Select({
        "select",
        "itemId, orderId, productId, productName, originPrice, shopPrice, productCount, ",
        "productIcon, createTime, updateTime",
        "from order_item",
        "where itemId = #{itemId,jdbcType=VARCHAR}"
    })
    @Results({
        @Result(column="itemId", property="itemId", jdbcType=JdbcType.VARCHAR, id=true),
        @Result(column="orderId", property="orderId", jdbcType=JdbcType.VARCHAR),
        @Result(column="productId", property="productId", jdbcType=JdbcType.VARCHAR),
        @Result(column="productName", property="productName", jdbcType=JdbcType.VARCHAR),
        @Result(column="originPrice", property="originPrice", jdbcType=JdbcType.DECIMAL),
        @Result(column="shopPrice", property="shopPrice", jdbcType=JdbcType.DECIMAL),
        @Result(column="productCount", property="productCount", jdbcType=JdbcType.INTEGER),
        @Result(column="productIcon", property="productIcon", jdbcType=JdbcType.VARCHAR),
        @Result(column="createTime", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="updateTime", property="updateTime", jdbcType=JdbcType.TIMESTAMP)
    })
    OrderItem selectByPrimaryKey(String itemId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbg.generated Sat Apr 20 10:25:51 CST 2019
     */
    @UpdateProvider(type=OrderItemSqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") OrderItem record, @Param("example") OrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbg.generated Sat Apr 20 10:25:51 CST 2019
     */
    @UpdateProvider(type=OrderItemSqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") OrderItem record, @Param("example") OrderItemExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbg.generated Sat Apr 20 10:25:51 CST 2019
     */
    @UpdateProvider(type=OrderItemSqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(OrderItem record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbg.generated Sat Apr 20 10:25:51 CST 2019
     */
    @Update({
        "update order_item",
        "set orderId = #{orderId,jdbcType=VARCHAR},",
          "productId = #{productId,jdbcType=VARCHAR},",
          "productName = #{productName,jdbcType=VARCHAR},",
          "originPrice = #{originPrice,jdbcType=DECIMAL},",
          "shopPrice = #{shopPrice,jdbcType=DECIMAL},",
          "productCount = #{productCount,jdbcType=INTEGER},",
          "productIcon = #{productIcon,jdbcType=VARCHAR},",
          "createTime = #{createTime,jdbcType=TIMESTAMP},",
          "updateTime = #{updateTime,jdbcType=TIMESTAMP}",
        "where itemId = #{itemId,jdbcType=VARCHAR}"
    })
    int updateByPrimaryKey(OrderItem record);
}