package com.benxiaopao.provider.dao.map;

import com.benxiaopao.provider.dao.model.OrderItem;
import com.benxiaopao.provider.dao.model.OrderItemExample.Criteria;
import com.benxiaopao.provider.dao.model.OrderItemExample.Criterion;
import com.benxiaopao.provider.dao.model.OrderItemExample;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class OrderItemSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbg.generated Sat Apr 20 10:25:51 CST 2019
     */
    public String countByExample(OrderItemExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("order_item");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbg.generated Sat Apr 20 10:25:51 CST 2019
     */
    public String deleteByExample(OrderItemExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("order_item");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbg.generated Sat Apr 20 10:25:51 CST 2019
     */
    public String insertSelective(OrderItem record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("order_item");
        
        if (record.getItemId() != null) {
            sql.VALUES("itemId", "#{itemId,jdbcType=VARCHAR}");
        }
        
        if (record.getOrderId() != null) {
            sql.VALUES("orderId", "#{orderId,jdbcType=VARCHAR}");
        }
        
        if (record.getProductId() != null) {
            sql.VALUES("productId", "#{productId,jdbcType=VARCHAR}");
        }
        
        if (record.getProductName() != null) {
            sql.VALUES("productName", "#{productName,jdbcType=VARCHAR}");
        }
        
        if (record.getOriginPrice() != null) {
            sql.VALUES("originPrice", "#{originPrice,jdbcType=DECIMAL}");
        }
        
        if (record.getShopPrice() != null) {
            sql.VALUES("shopPrice", "#{shopPrice,jdbcType=DECIMAL}");
        }
        
        if (record.getProductCount() != null) {
            sql.VALUES("productCount", "#{productCount,jdbcType=INTEGER}");
        }
        
        if (record.getProductIcon() != null) {
            sql.VALUES("productIcon", "#{productIcon,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateTime() != null) {
            sql.VALUES("createTime", "#{createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdateTime() != null) {
            sql.VALUES("updateTime", "#{updateTime,jdbcType=TIMESTAMP}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbg.generated Sat Apr 20 10:25:51 CST 2019
     */
    public String selectByExample(OrderItemExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("itemId");
        } else {
            sql.SELECT("itemId");
        }
        sql.SELECT("orderId");
        sql.SELECT("productId");
        sql.SELECT("productName");
        sql.SELECT("originPrice");
        sql.SELECT("shopPrice");
        sql.SELECT("productCount");
        sql.SELECT("productIcon");
        sql.SELECT("createTime");
        sql.SELECT("updateTime");
        sql.FROM("order_item");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbg.generated Sat Apr 20 10:25:51 CST 2019
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        OrderItem record = (OrderItem) parameter.get("record");
        OrderItemExample example = (OrderItemExample) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("order_item");
        
        if (record.getItemId() != null) {
            sql.SET("itemId = #{record.itemId,jdbcType=VARCHAR}");
        }
        
        if (record.getOrderId() != null) {
            sql.SET("orderId = #{record.orderId,jdbcType=VARCHAR}");
        }
        
        if (record.getProductId() != null) {
            sql.SET("productId = #{record.productId,jdbcType=VARCHAR}");
        }
        
        if (record.getProductName() != null) {
            sql.SET("productName = #{record.productName,jdbcType=VARCHAR}");
        }
        
        if (record.getOriginPrice() != null) {
            sql.SET("originPrice = #{record.originPrice,jdbcType=DECIMAL}");
        }
        
        if (record.getShopPrice() != null) {
            sql.SET("shopPrice = #{record.shopPrice,jdbcType=DECIMAL}");
        }
        
        if (record.getProductCount() != null) {
            sql.SET("productCount = #{record.productCount,jdbcType=INTEGER}");
        }
        
        if (record.getProductIcon() != null) {
            sql.SET("productIcon = #{record.productIcon,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateTime() != null) {
            sql.SET("createTime = #{record.createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdateTime() != null) {
            sql.SET("updateTime = #{record.updateTime,jdbcType=TIMESTAMP}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbg.generated Sat Apr 20 10:25:51 CST 2019
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("order_item");
        
        sql.SET("itemId = #{record.itemId,jdbcType=VARCHAR}");
        sql.SET("orderId = #{record.orderId,jdbcType=VARCHAR}");
        sql.SET("productId = #{record.productId,jdbcType=VARCHAR}");
        sql.SET("productName = #{record.productName,jdbcType=VARCHAR}");
        sql.SET("originPrice = #{record.originPrice,jdbcType=DECIMAL}");
        sql.SET("shopPrice = #{record.shopPrice,jdbcType=DECIMAL}");
        sql.SET("productCount = #{record.productCount,jdbcType=INTEGER}");
        sql.SET("productIcon = #{record.productIcon,jdbcType=VARCHAR}");
        sql.SET("createTime = #{record.createTime,jdbcType=TIMESTAMP}");
        sql.SET("updateTime = #{record.updateTime,jdbcType=TIMESTAMP}");
        
        OrderItemExample example = (OrderItemExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbg.generated Sat Apr 20 10:25:51 CST 2019
     */
    public String updateByPrimaryKeySelective(OrderItem record) {
        SQL sql = new SQL();
        sql.UPDATE("order_item");
        
        if (record.getOrderId() != null) {
            sql.SET("orderId = #{orderId,jdbcType=VARCHAR}");
        }
        
        if (record.getProductId() != null) {
            sql.SET("productId = #{productId,jdbcType=VARCHAR}");
        }
        
        if (record.getProductName() != null) {
            sql.SET("productName = #{productName,jdbcType=VARCHAR}");
        }
        
        if (record.getOriginPrice() != null) {
            sql.SET("originPrice = #{originPrice,jdbcType=DECIMAL}");
        }
        
        if (record.getShopPrice() != null) {
            sql.SET("shopPrice = #{shopPrice,jdbcType=DECIMAL}");
        }
        
        if (record.getProductCount() != null) {
            sql.SET("productCount = #{productCount,jdbcType=INTEGER}");
        }
        
        if (record.getProductIcon() != null) {
            sql.SET("productIcon = #{productIcon,jdbcType=VARCHAR}");
        }
        
        if (record.getCreateTime() != null) {
            sql.SET("createTime = #{createTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getUpdateTime() != null) {
            sql.SET("updateTime = #{updateTime,jdbcType=TIMESTAMP}");
        }
        
        sql.WHERE("itemId = #{itemId,jdbcType=VARCHAR}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table order_item
     *
     * @mbg.generated Sat Apr 20 10:25:51 CST 2019
     */
    protected void applyWhere(SQL sql, OrderItemExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}