package com.benxiaopao.provider.dao.map;

import com.benxiaopao.provider.dao.model.ProductCategory;
import com.benxiaopao.provider.dao.model.ProductCategoryExample;
import java.util.List;
import org.apache.ibatis.annotations.Delete;
import org.apache.ibatis.annotations.DeleteProvider;
import org.apache.ibatis.annotations.Insert;
import org.apache.ibatis.annotations.InsertProvider;
import org.apache.ibatis.annotations.Param;
import org.apache.ibatis.annotations.Result;
import org.apache.ibatis.annotations.Results;
import org.apache.ibatis.annotations.Select;
import org.apache.ibatis.annotations.SelectProvider;
import org.apache.ibatis.annotations.Update;
import org.apache.ibatis.annotations.UpdateProvider;
import org.apache.ibatis.type.JdbcType;

public interface ProductCategoryMapper {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_category
     *
     * @mbg.generated Sat Apr 20 10:24:44 CST 2019
     */
    @SelectProvider(type=ProductCategorySqlProvider.class, method="countByExample")
    long countByExample(ProductCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_category
     *
     * @mbg.generated Sat Apr 20 10:24:44 CST 2019
     */
    @DeleteProvider(type=ProductCategorySqlProvider.class, method="deleteByExample")
    int deleteByExample(ProductCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_category
     *
     * @mbg.generated Sat Apr 20 10:24:44 CST 2019
     */
    @Delete({
        "delete from product_category",
        "where categoryId = #{categoryId,jdbcType=INTEGER}"
    })
    int deleteByPrimaryKey(Integer categoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_category
     *
     * @mbg.generated Sat Apr 20 10:24:44 CST 2019
     */
    @Insert({
        "insert into product_category (categoryId, categoryName, ",
        "categoryType, restaurantId, ",
        "createTime, updateTime)",
        "values (#{categoryId,jdbcType=INTEGER}, #{categoryName,jdbcType=VARCHAR}, ",
        "#{categoryType,jdbcType=INTEGER}, #{restaurantId,jdbcType=INTEGER}, ",
        "#{createTime,jdbcType=TIMESTAMP}, #{updateTime,jdbcType=TIMESTAMP})"
    })
    int insert(ProductCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_category
     *
     * @mbg.generated Sat Apr 20 10:24:44 CST 2019
     */
    @InsertProvider(type=ProductCategorySqlProvider.class, method="insertSelective")
    int insertSelective(ProductCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_category
     *
     * @mbg.generated Sat Apr 20 10:24:44 CST 2019
     */
    @SelectProvider(type=ProductCategorySqlProvider.class, method="selectByExample")
    @Results({
        @Result(column="categoryId", property="categoryId", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="categoryName", property="categoryName", jdbcType=JdbcType.VARCHAR),
        @Result(column="categoryType", property="categoryType", jdbcType=JdbcType.INTEGER),
        @Result(column="restaurantId", property="restaurantId", jdbcType=JdbcType.INTEGER),
        @Result(column="createTime", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="updateTime", property="updateTime", jdbcType=JdbcType.TIMESTAMP)
    })
    List<ProductCategory> selectByExample(ProductCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_category
     *
     * @mbg.generated Sat Apr 20 10:24:44 CST 2019
     */
    @Select({
        "select",
        "categoryId, categoryName, categoryType, restaurantId, createTime, updateTime",
        "from product_category",
        "where categoryId = #{categoryId,jdbcType=INTEGER}"
    })
    @Results({
        @Result(column="categoryId", property="categoryId", jdbcType=JdbcType.INTEGER, id=true),
        @Result(column="categoryName", property="categoryName", jdbcType=JdbcType.VARCHAR),
        @Result(column="categoryType", property="categoryType", jdbcType=JdbcType.INTEGER),
        @Result(column="restaurantId", property="restaurantId", jdbcType=JdbcType.INTEGER),
        @Result(column="createTime", property="createTime", jdbcType=JdbcType.TIMESTAMP),
        @Result(column="updateTime", property="updateTime", jdbcType=JdbcType.TIMESTAMP)
    })
    ProductCategory selectByPrimaryKey(Integer categoryId);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_category
     *
     * @mbg.generated Sat Apr 20 10:24:44 CST 2019
     */
    @UpdateProvider(type=ProductCategorySqlProvider.class, method="updateByExampleSelective")
    int updateByExampleSelective(@Param("record") ProductCategory record, @Param("example") ProductCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_category
     *
     * @mbg.generated Sat Apr 20 10:24:44 CST 2019
     */
    @UpdateProvider(type=ProductCategorySqlProvider.class, method="updateByExample")
    int updateByExample(@Param("record") ProductCategory record, @Param("example") ProductCategoryExample example);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_category
     *
     * @mbg.generated Sat Apr 20 10:24:44 CST 2019
     */
    @UpdateProvider(type=ProductCategorySqlProvider.class, method="updateByPrimaryKeySelective")
    int updateByPrimaryKeySelective(ProductCategory record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table product_category
     *
     * @mbg.generated Sat Apr 20 10:24:44 CST 2019
     */
    @Update({
        "update product_category",
        "set categoryName = #{categoryName,jdbcType=VARCHAR},",
          "categoryType = #{categoryType,jdbcType=INTEGER},",
          "restaurantId = #{restaurantId,jdbcType=INTEGER},",
          "createTime = #{createTime,jdbcType=TIMESTAMP},",
          "updateTime = #{updateTime,jdbcType=TIMESTAMP}",
        "where categoryId = #{categoryId,jdbcType=INTEGER}"
    })
    int updateByPrimaryKey(ProductCategory record);
}