package com.benxiaopao.provider.dao.map;

import com.benxiaopao.provider.dao.model.User;
import com.benxiaopao.provider.dao.model.UserExample.Criteria;
import com.benxiaopao.provider.dao.model.UserExample.Criterion;
import com.benxiaopao.provider.dao.model.UserExample;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class UserSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Sat Apr 20 10:26:44 CST 2019
     */
    public String countByExample(UserExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("user_info");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Sat Apr 20 10:26:44 CST 2019
     */
    public String deleteByExample(UserExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("user_info");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Sat Apr 20 10:26:44 CST 2019
     */
    public String insertSelective(User record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("user_info");
        
        if (record.getUserId() != null) {
            sql.VALUES("userId", "#{userId,jdbcType=INTEGER}");
        }
        
        if (record.getEmail() != null) {
            sql.VALUES("email", "#{email,jdbcType=VARCHAR}");
        }
        
        if (record.getNickName() != null) {
            sql.VALUES("nickName", "#{nickName,jdbcType=VARCHAR}");
        }
        
        if (record.getRealName() != null) {
            sql.VALUES("realName", "#{realName,jdbcType=VARCHAR}");
        }
        
        if (record.getDisplayName() != null) {
            sql.VALUES("displayName", "#{displayName,jdbcType=VARCHAR}");
        }
        
        if (record.getPassword() != null) {
            sql.VALUES("password", "#{password,jdbcType=VARCHAR}");
        }
        
        if (record.getMobile() != null) {
            sql.VALUES("mobile", "#{mobile,jdbcType=VARCHAR}");
        }
        
        if (record.getCity() != null) {
            sql.VALUES("city", "#{city,jdbcType=VARCHAR}");
        }
        
        if (record.getRegisterTime() != null) {
            sql.VALUES("registerTime", "#{registerTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getActiveTime() != null) {
            sql.VALUES("activeTime", "#{activeTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getStatus() != null) {
            sql.VALUES("status", "#{status,jdbcType=SMALLINT}");
        }
        
        if (record.getForbidStatus() != null) {
            sql.VALUES("forbidStatus", "#{forbidStatus,jdbcType=SMALLINT}");
        }
        
        if (record.getSecurityLevel() != null) {
            sql.VALUES("securityLevel", "#{securityLevel,jdbcType=SMALLINT}");
        }
        
        if (record.getWeiboUId() != null) {
            sql.VALUES("weiboUId", "#{weiboUId,jdbcType=VARCHAR}");
        }
        
        if (record.getWeiboAccessToken() != null) {
            sql.VALUES("weiboAccessToken", "#{weiboAccessToken,jdbcType=VARCHAR}");
        }
        
        if (record.getQqUId() != null) {
            sql.VALUES("qqUId", "#{qqUId,jdbcType=VARCHAR}");
        }
        
        if (record.getQqAccessToken() != null) {
            sql.VALUES("qqAccessToken", "#{qqAccessToken,jdbcType=VARCHAR}");
        }
        
        if (record.getRegisterChannelId() != null) {
            sql.VALUES("registerChannelId", "#{registerChannelId,jdbcType=VARCHAR}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Sat Apr 20 10:26:44 CST 2019
     */
    public String selectByExample(UserExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("userId");
        } else {
            sql.SELECT("userId");
        }
        sql.SELECT("email");
        sql.SELECT("nickName");
        sql.SELECT("realName");
        sql.SELECT("displayName");
        sql.SELECT("password");
        sql.SELECT("mobile");
        sql.SELECT("city");
        sql.SELECT("registerTime");
        sql.SELECT("activeTime");
        sql.SELECT("status");
        sql.SELECT("forbidStatus");
        sql.SELECT("securityLevel");
        sql.SELECT("weiboUId");
        sql.SELECT("weiboAccessToken");
        sql.SELECT("qqUId");
        sql.SELECT("qqAccessToken");
        sql.SELECT("registerChannelId");
        sql.FROM("user_info");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Sat Apr 20 10:26:44 CST 2019
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        User record = (User) parameter.get("record");
        UserExample example = (UserExample) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("user_info");
        
        if (record.getUserId() != null) {
            sql.SET("userId = #{record.userId,jdbcType=INTEGER}");
        }
        
        if (record.getEmail() != null) {
            sql.SET("email = #{record.email,jdbcType=VARCHAR}");
        }
        
        if (record.getNickName() != null) {
            sql.SET("nickName = #{record.nickName,jdbcType=VARCHAR}");
        }
        
        if (record.getRealName() != null) {
            sql.SET("realName = #{record.realName,jdbcType=VARCHAR}");
        }
        
        if (record.getDisplayName() != null) {
            sql.SET("displayName = #{record.displayName,jdbcType=VARCHAR}");
        }
        
        if (record.getPassword() != null) {
            sql.SET("password = #{record.password,jdbcType=VARCHAR}");
        }
        
        if (record.getMobile() != null) {
            sql.SET("mobile = #{record.mobile,jdbcType=VARCHAR}");
        }
        
        if (record.getCity() != null) {
            sql.SET("city = #{record.city,jdbcType=VARCHAR}");
        }
        
        if (record.getRegisterTime() != null) {
            sql.SET("registerTime = #{record.registerTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getActiveTime() != null) {
            sql.SET("activeTime = #{record.activeTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getStatus() != null) {
            sql.SET("status = #{record.status,jdbcType=SMALLINT}");
        }
        
        if (record.getForbidStatus() != null) {
            sql.SET("forbidStatus = #{record.forbidStatus,jdbcType=SMALLINT}");
        }
        
        if (record.getSecurityLevel() != null) {
            sql.SET("securityLevel = #{record.securityLevel,jdbcType=SMALLINT}");
        }
        
        if (record.getWeiboUId() != null) {
            sql.SET("weiboUId = #{record.weiboUId,jdbcType=VARCHAR}");
        }
        
        if (record.getWeiboAccessToken() != null) {
            sql.SET("weiboAccessToken = #{record.weiboAccessToken,jdbcType=VARCHAR}");
        }
        
        if (record.getQqUId() != null) {
            sql.SET("qqUId = #{record.qqUId,jdbcType=VARCHAR}");
        }
        
        if (record.getQqAccessToken() != null) {
            sql.SET("qqAccessToken = #{record.qqAccessToken,jdbcType=VARCHAR}");
        }
        
        if (record.getRegisterChannelId() != null) {
            sql.SET("registerChannelId = #{record.registerChannelId,jdbcType=VARCHAR}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Sat Apr 20 10:26:44 CST 2019
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("user_info");
        
        sql.SET("userId = #{record.userId,jdbcType=INTEGER}");
        sql.SET("email = #{record.email,jdbcType=VARCHAR}");
        sql.SET("nickName = #{record.nickName,jdbcType=VARCHAR}");
        sql.SET("realName = #{record.realName,jdbcType=VARCHAR}");
        sql.SET("displayName = #{record.displayName,jdbcType=VARCHAR}");
        sql.SET("password = #{record.password,jdbcType=VARCHAR}");
        sql.SET("mobile = #{record.mobile,jdbcType=VARCHAR}");
        sql.SET("city = #{record.city,jdbcType=VARCHAR}");
        sql.SET("registerTime = #{record.registerTime,jdbcType=TIMESTAMP}");
        sql.SET("activeTime = #{record.activeTime,jdbcType=TIMESTAMP}");
        sql.SET("status = #{record.status,jdbcType=SMALLINT}");
        sql.SET("forbidStatus = #{record.forbidStatus,jdbcType=SMALLINT}");
        sql.SET("securityLevel = #{record.securityLevel,jdbcType=SMALLINT}");
        sql.SET("weiboUId = #{record.weiboUId,jdbcType=VARCHAR}");
        sql.SET("weiboAccessToken = #{record.weiboAccessToken,jdbcType=VARCHAR}");
        sql.SET("qqUId = #{record.qqUId,jdbcType=VARCHAR}");
        sql.SET("qqAccessToken = #{record.qqAccessToken,jdbcType=VARCHAR}");
        sql.SET("registerChannelId = #{record.registerChannelId,jdbcType=VARCHAR}");
        
        UserExample example = (UserExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Sat Apr 20 10:26:44 CST 2019
     */
    public String updateByPrimaryKeySelective(User record) {
        SQL sql = new SQL();
        sql.UPDATE("user_info");
        
        if (record.getEmail() != null) {
            sql.SET("email = #{email,jdbcType=VARCHAR}");
        }
        
        if (record.getNickName() != null) {
            sql.SET("nickName = #{nickName,jdbcType=VARCHAR}");
        }
        
        if (record.getRealName() != null) {
            sql.SET("realName = #{realName,jdbcType=VARCHAR}");
        }
        
        if (record.getDisplayName() != null) {
            sql.SET("displayName = #{displayName,jdbcType=VARCHAR}");
        }
        
        if (record.getPassword() != null) {
            sql.SET("password = #{password,jdbcType=VARCHAR}");
        }
        
        if (record.getMobile() != null) {
            sql.SET("mobile = #{mobile,jdbcType=VARCHAR}");
        }
        
        if (record.getCity() != null) {
            sql.SET("city = #{city,jdbcType=VARCHAR}");
        }
        
        if (record.getRegisterTime() != null) {
            sql.SET("registerTime = #{registerTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getActiveTime() != null) {
            sql.SET("activeTime = #{activeTime,jdbcType=TIMESTAMP}");
        }
        
        if (record.getStatus() != null) {
            sql.SET("status = #{status,jdbcType=SMALLINT}");
        }
        
        if (record.getForbidStatus() != null) {
            sql.SET("forbidStatus = #{forbidStatus,jdbcType=SMALLINT}");
        }
        
        if (record.getSecurityLevel() != null) {
            sql.SET("securityLevel = #{securityLevel,jdbcType=SMALLINT}");
        }
        
        if (record.getWeiboUId() != null) {
            sql.SET("weiboUId = #{weiboUId,jdbcType=VARCHAR}");
        }
        
        if (record.getWeiboAccessToken() != null) {
            sql.SET("weiboAccessToken = #{weiboAccessToken,jdbcType=VARCHAR}");
        }
        
        if (record.getQqUId() != null) {
            sql.SET("qqUId = #{qqUId,jdbcType=VARCHAR}");
        }
        
        if (record.getQqAccessToken() != null) {
            sql.SET("qqAccessToken = #{qqAccessToken,jdbcType=VARCHAR}");
        }
        
        if (record.getRegisterChannelId() != null) {
            sql.SET("registerChannelId = #{registerChannelId,jdbcType=VARCHAR}");
        }
        
        sql.WHERE("userId = #{userId,jdbcType=INTEGER}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Sat Apr 20 10:26:44 CST 2019
     */
    protected void applyWhere(SQL sql, UserExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}