package com.benxiaopao.provider.dao.map;

import com.benxiaopao.provider.dao.model.UserLoginIp;
import com.benxiaopao.provider.dao.model.UserLoginIpExample.Criteria;
import com.benxiaopao.provider.dao.model.UserLoginIpExample.Criterion;
import com.benxiaopao.provider.dao.model.UserLoginIpExample;
import java.util.List;
import java.util.Map;
import org.apache.ibatis.jdbc.SQL;

public class UserLoginIpSqlProvider {

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login_ip
     *
     * @mbg.generated Sun May 05 00:45:31 CST 2019
     */
    public String countByExample(UserLoginIpExample example) {
        SQL sql = new SQL();
        sql.SELECT("count(*)").FROM("user_login_ip");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login_ip
     *
     * @mbg.generated Sun May 05 00:45:31 CST 2019
     */
    public String deleteByExample(UserLoginIpExample example) {
        SQL sql = new SQL();
        sql.DELETE_FROM("user_login_ip");
        applyWhere(sql, example, false);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login_ip
     *
     * @mbg.generated Sun May 05 00:45:31 CST 2019
     */
    public String insertSelective(UserLoginIp record) {
        SQL sql = new SQL();
        sql.INSERT_INTO("user_login_ip");
        
        if (record.getIpId() != null) {
            sql.VALUES("ipId", "#{ipId,jdbcType=INTEGER}");
        }
        
        if (record.getUserId() != null) {
            sql.VALUES("userId", "#{userId,jdbcType=INTEGER}");
        }
        
        if (record.getLoginIP() != null) {
            sql.VALUES("loginIP", "#{loginIP,jdbcType=BIGINT}");
        }
        
        if (record.getBrowserType() != null) {
            sql.VALUES("browserType", "#{browserType,jdbcType=SMALLINT}");
        }
        
        if (record.getOsType() != null) {
            sql.VALUES("osType", "#{osType,jdbcType=SMALLINT}");
        }
        
        if (record.getLoginAddress() != null) {
            sql.VALUES("loginAddress", "#{loginAddress,jdbcType=VARCHAR}");
        }
        
        if (record.getLoginTime() != null) {
            sql.VALUES("loginTime", "#{loginTime,jdbcType=TIMESTAMP}");
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login_ip
     *
     * @mbg.generated Sun May 05 00:45:31 CST 2019
     */
    public String selectByExample(UserLoginIpExample example) {
        SQL sql = new SQL();
        if (example != null && example.isDistinct()) {
            sql.SELECT_DISTINCT("ipId");
        } else {
            sql.SELECT("ipId");
        }
        sql.SELECT("userId");
        sql.SELECT("loginIP");
        sql.SELECT("browserType");
        sql.SELECT("osType");
        sql.SELECT("loginAddress");
        sql.SELECT("loginTime");
        sql.FROM("user_login_ip");
        applyWhere(sql, example, false);
        
        if (example != null && example.getOrderByClause() != null) {
            sql.ORDER_BY(example.getOrderByClause());
        }
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login_ip
     *
     * @mbg.generated Sun May 05 00:45:31 CST 2019
     */
    public String updateByExampleSelective(Map<String, Object> parameter) {
        UserLoginIp record = (UserLoginIp) parameter.get("record");
        UserLoginIpExample example = (UserLoginIpExample) parameter.get("example");
        
        SQL sql = new SQL();
        sql.UPDATE("user_login_ip");
        
        if (record.getIpId() != null) {
            sql.SET("ipId = #{record.ipId,jdbcType=INTEGER}");
        }
        
        if (record.getUserId() != null) {
            sql.SET("userId = #{record.userId,jdbcType=INTEGER}");
        }
        
        if (record.getLoginIP() != null) {
            sql.SET("loginIP = #{record.loginIP,jdbcType=BIGINT}");
        }
        
        if (record.getBrowserType() != null) {
            sql.SET("browserType = #{record.browserType,jdbcType=SMALLINT}");
        }
        
        if (record.getOsType() != null) {
            sql.SET("osType = #{record.osType,jdbcType=SMALLINT}");
        }
        
        if (record.getLoginAddress() != null) {
            sql.SET("loginAddress = #{record.loginAddress,jdbcType=VARCHAR}");
        }
        
        if (record.getLoginTime() != null) {
            sql.SET("loginTime = #{record.loginTime,jdbcType=TIMESTAMP}");
        }
        
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login_ip
     *
     * @mbg.generated Sun May 05 00:45:31 CST 2019
     */
    public String updateByExample(Map<String, Object> parameter) {
        SQL sql = new SQL();
        sql.UPDATE("user_login_ip");
        
        sql.SET("ipId = #{record.ipId,jdbcType=INTEGER}");
        sql.SET("userId = #{record.userId,jdbcType=INTEGER}");
        sql.SET("loginIP = #{record.loginIP,jdbcType=BIGINT}");
        sql.SET("browserType = #{record.browserType,jdbcType=SMALLINT}");
        sql.SET("osType = #{record.osType,jdbcType=SMALLINT}");
        sql.SET("loginAddress = #{record.loginAddress,jdbcType=VARCHAR}");
        sql.SET("loginTime = #{record.loginTime,jdbcType=TIMESTAMP}");
        
        UserLoginIpExample example = (UserLoginIpExample) parameter.get("example");
        applyWhere(sql, example, true);
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login_ip
     *
     * @mbg.generated Sun May 05 00:45:31 CST 2019
     */
    public String updateByPrimaryKeySelective(UserLoginIp record) {
        SQL sql = new SQL();
        sql.UPDATE("user_login_ip");
        
        if (record.getUserId() != null) {
            sql.SET("userId = #{userId,jdbcType=INTEGER}");
        }
        
        if (record.getLoginIP() != null) {
            sql.SET("loginIP = #{loginIP,jdbcType=BIGINT}");
        }
        
        if (record.getBrowserType() != null) {
            sql.SET("browserType = #{browserType,jdbcType=SMALLINT}");
        }
        
        if (record.getOsType() != null) {
            sql.SET("osType = #{osType,jdbcType=SMALLINT}");
        }
        
        if (record.getLoginAddress() != null) {
            sql.SET("loginAddress = #{loginAddress,jdbcType=VARCHAR}");
        }
        
        if (record.getLoginTime() != null) {
            sql.SET("loginTime = #{loginTime,jdbcType=TIMESTAMP}");
        }
        
        sql.WHERE("ipId = #{ipId,jdbcType=INTEGER}");
        
        return sql.toString();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login_ip
     *
     * @mbg.generated Sun May 05 00:45:31 CST 2019
     */
    protected void applyWhere(SQL sql, UserLoginIpExample example, boolean includeExamplePhrase) {
        if (example == null) {
            return;
        }
        
        String parmPhrase1;
        String parmPhrase1_th;
        String parmPhrase2;
        String parmPhrase2_th;
        String parmPhrase3;
        String parmPhrase3_th;
        if (includeExamplePhrase) {
            parmPhrase1 = "%s #{example.oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{example.oredCriteria[%d].allCriteria[%d].value} and #{example.oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{example.oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{example.oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{example.oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{example.oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        } else {
            parmPhrase1 = "%s #{oredCriteria[%d].allCriteria[%d].value}";
            parmPhrase1_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s}";
            parmPhrase2 = "%s #{oredCriteria[%d].allCriteria[%d].value} and #{oredCriteria[%d].criteria[%d].secondValue}";
            parmPhrase2_th = "%s #{oredCriteria[%d].allCriteria[%d].value,typeHandler=%s} and #{oredCriteria[%d].criteria[%d].secondValue,typeHandler=%s}";
            parmPhrase3 = "#{oredCriteria[%d].allCriteria[%d].value[%d]}";
            parmPhrase3_th = "#{oredCriteria[%d].allCriteria[%d].value[%d],typeHandler=%s}";
        }
        
        StringBuilder sb = new StringBuilder();
        List<Criteria> oredCriteria = example.getOredCriteria();
        boolean firstCriteria = true;
        for (int i = 0; i < oredCriteria.size(); i++) {
            Criteria criteria = oredCriteria.get(i);
            if (criteria.isValid()) {
                if (firstCriteria) {
                    firstCriteria = false;
                } else {
                    sb.append(" or ");
                }
                
                sb.append('(');
                List<Criterion> criterions = criteria.getAllCriteria();
                boolean firstCriterion = true;
                for (int j = 0; j < criterions.size(); j++) {
                    Criterion criterion = criterions.get(j);
                    if (firstCriterion) {
                        firstCriterion = false;
                    } else {
                        sb.append(" and ");
                    }
                    
                    if (criterion.isNoValue()) {
                        sb.append(criterion.getCondition());
                    } else if (criterion.isSingleValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase1, criterion.getCondition(), i, j));
                        } else {
                            sb.append(String.format(parmPhrase1_th, criterion.getCondition(), i, j,criterion.getTypeHandler()));
                        }
                    } else if (criterion.isBetweenValue()) {
                        if (criterion.getTypeHandler() == null) {
                            sb.append(String.format(parmPhrase2, criterion.getCondition(), i, j, i, j));
                        } else {
                            sb.append(String.format(parmPhrase2_th, criterion.getCondition(), i, j, criterion.getTypeHandler(), i, j, criterion.getTypeHandler()));
                        }
                    } else if (criterion.isListValue()) {
                        sb.append(criterion.getCondition());
                        sb.append(" (");
                        List<?> listItems = (List<?>) criterion.getValue();
                        boolean comma = false;
                        for (int k = 0; k < listItems.size(); k++) {
                            if (comma) {
                                sb.append(", ");
                            } else {
                                comma = true;
                            }
                            if (criterion.getTypeHandler() == null) {
                                sb.append(String.format(parmPhrase3, i, j, k));
                            } else {
                                sb.append(String.format(parmPhrase3_th, i, j, k, criterion.getTypeHandler()));
                            }
                        }
                        sb.append(')');
                    }
                }
                sb.append(')');
            }
        }
        
        if (sb.length() > 0) {
            sql.WHERE(sb.toString());
        }
    }
}