package com.benxiaopao.provider.dao.model;

import java.util.Date;

public class MobileAuthen {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_authen.mobileAuthenId
     *
     * @mbg.generated Sat Apr 20 10:27:14 CST 2019
     */
    private Long mobileAuthenId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_authen.mobile
     *
     * @mbg.generated Sat Apr 20 10:27:14 CST 2019
     */
    private String mobile;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_authen.sendTime
     *
     * @mbg.generated Sat Apr 20 10:27:14 CST 2019
     */
    private Date sendTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_authen.validCode
     *
     * @mbg.generated Sat Apr 20 10:27:14 CST 2019
     */
    private String validCode;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column mobile_authen.userId
     *
     * @mbg.generated Sat Apr 20 10:27:14 CST 2019
     */
    private Integer userId;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_authen.mobileAuthenId
     *
     * @return the value of mobile_authen.mobileAuthenId
     *
     * @mbg.generated Sat Apr 20 10:27:14 CST 2019
     */
    public Long getMobileAuthenId() {
        return mobileAuthenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_authen.mobileAuthenId
     *
     * @param mobileAuthenId the value for mobile_authen.mobileAuthenId
     *
     * @mbg.generated Sat Apr 20 10:27:14 CST 2019
     */
    public void setMobileAuthenId(Long mobileAuthenId) {
        this.mobileAuthenId = mobileAuthenId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_authen.mobile
     *
     * @return the value of mobile_authen.mobile
     *
     * @mbg.generated Sat Apr 20 10:27:14 CST 2019
     */
    public String getMobile() {
        return mobile;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_authen.mobile
     *
     * @param mobile the value for mobile_authen.mobile
     *
     * @mbg.generated Sat Apr 20 10:27:14 CST 2019
     */
    public void setMobile(String mobile) {
        this.mobile = mobile == null ? null : mobile.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_authen.sendTime
     *
     * @return the value of mobile_authen.sendTime
     *
     * @mbg.generated Sat Apr 20 10:27:14 CST 2019
     */
    public Date getSendTime() {
        return sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_authen.sendTime
     *
     * @param sendTime the value for mobile_authen.sendTime
     *
     * @mbg.generated Sat Apr 20 10:27:14 CST 2019
     */
    public void setSendTime(Date sendTime) {
        this.sendTime = sendTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_authen.validCode
     *
     * @return the value of mobile_authen.validCode
     *
     * @mbg.generated Sat Apr 20 10:27:14 CST 2019
     */
    public String getValidCode() {
        return validCode;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_authen.validCode
     *
     * @param validCode the value for mobile_authen.validCode
     *
     * @mbg.generated Sat Apr 20 10:27:14 CST 2019
     */
    public void setValidCode(String validCode) {
        this.validCode = validCode == null ? null : validCode.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column mobile_authen.userId
     *
     * @return the value of mobile_authen.userId
     *
     * @mbg.generated Sat Apr 20 10:27:14 CST 2019
     */
    public Integer getUserId() {
        return userId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column mobile_authen.userId
     *
     * @param userId the value for mobile_authen.userId
     *
     * @mbg.generated Sat Apr 20 10:27:14 CST 2019
     */
    public void setUserId(Integer userId) {
        this.userId = userId;
    }
}