package com.benxiaopao.provider.dao.model;

import java.math.BigDecimal;
import java.util.Date;

public class Order {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.orderId
     *
     * @mbg.generated Sat Apr 20 10:25:29 CST 2019
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.payType
     *
     * @mbg.generated Sat Apr 20 10:25:29 CST 2019
     */
    private Integer payType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.totalAmout
     *
     * @mbg.generated Sat Apr 20 10:25:29 CST 2019
     */
    private BigDecimal totalAmout;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.realTotalAmout
     *
     * @mbg.generated Sat Apr 20 10:25:29 CST 2019
     */
    private BigDecimal realTotalAmout;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.shipmentExpense
     *
     * @mbg.generated Sat Apr 20 10:25:29 CST 2019
     */
    private BigDecimal shipmentExpense;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.orderStatus
     *
     * @mbg.generated Sat Apr 20 10:25:29 CST 2019
     */
    private Short orderStatus;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.orderType
     *
     * @mbg.generated Sat Apr 20 10:25:29 CST 2019
     */
    private Byte orderType;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.orderFrom
     *
     * @mbg.generated Sat Apr 20 10:25:29 CST 2019
     */
    private Byte orderFrom;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.pOrderId
     *
     * @mbg.generated Sat Apr 20 10:25:29 CST 2019
     */
    private String pOrderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.buyerId
     *
     * @mbg.generated Sat Apr 20 10:25:29 CST 2019
     */
    private Integer buyerId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.consignee
     *
     * @mbg.generated Sat Apr 20 10:25:29 CST 2019
     */
    private String consignee;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.province
     *
     * @mbg.generated Sat Apr 20 10:25:29 CST 2019
     */
    private Integer province;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.city
     *
     * @mbg.generated Sat Apr 20 10:25:29 CST 2019
     */
    private Integer city;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.district
     *
     * @mbg.generated Sat Apr 20 10:25:29 CST 2019
     */
    private Integer district;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.address
     *
     * @mbg.generated Sat Apr 20 10:25:29 CST 2019
     */
    private String address;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.tel
     *
     * @mbg.generated Sat Apr 20 10:25:29 CST 2019
     */
    private String tel;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.createTime
     *
     * @mbg.generated Sat Apr 20 10:25:29 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_info.updateTime
     *
     * @mbg.generated Sat Apr 20 10:25:29 CST 2019
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.orderId
     *
     * @return the value of order_info.orderId
     *
     * @mbg.generated Sat Apr 20 10:25:29 CST 2019
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.orderId
     *
     * @param orderId the value for order_info.orderId
     *
     * @mbg.generated Sat Apr 20 10:25:29 CST 2019
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.payType
     *
     * @return the value of order_info.payType
     *
     * @mbg.generated Sat Apr 20 10:25:29 CST 2019
     */
    public Integer getPayType() {
        return payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.payType
     *
     * @param payType the value for order_info.payType
     *
     * @mbg.generated Sat Apr 20 10:25:29 CST 2019
     */
    public void setPayType(Integer payType) {
        this.payType = payType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.totalAmout
     *
     * @return the value of order_info.totalAmout
     *
     * @mbg.generated Sat Apr 20 10:25:29 CST 2019
     */
    public BigDecimal getTotalAmout() {
        return totalAmout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.totalAmout
     *
     * @param totalAmout the value for order_info.totalAmout
     *
     * @mbg.generated Sat Apr 20 10:25:29 CST 2019
     */
    public void setTotalAmout(BigDecimal totalAmout) {
        this.totalAmout = totalAmout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.realTotalAmout
     *
     * @return the value of order_info.realTotalAmout
     *
     * @mbg.generated Sat Apr 20 10:25:29 CST 2019
     */
    public BigDecimal getRealTotalAmout() {
        return realTotalAmout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.realTotalAmout
     *
     * @param realTotalAmout the value for order_info.realTotalAmout
     *
     * @mbg.generated Sat Apr 20 10:25:29 CST 2019
     */
    public void setRealTotalAmout(BigDecimal realTotalAmout) {
        this.realTotalAmout = realTotalAmout;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.shipmentExpense
     *
     * @return the value of order_info.shipmentExpense
     *
     * @mbg.generated Sat Apr 20 10:25:29 CST 2019
     */
    public BigDecimal getShipmentExpense() {
        return shipmentExpense;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.shipmentExpense
     *
     * @param shipmentExpense the value for order_info.shipmentExpense
     *
     * @mbg.generated Sat Apr 20 10:25:29 CST 2019
     */
    public void setShipmentExpense(BigDecimal shipmentExpense) {
        this.shipmentExpense = shipmentExpense;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.orderStatus
     *
     * @return the value of order_info.orderStatus
     *
     * @mbg.generated Sat Apr 20 10:25:29 CST 2019
     */
    public Short getOrderStatus() {
        return orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.orderStatus
     *
     * @param orderStatus the value for order_info.orderStatus
     *
     * @mbg.generated Sat Apr 20 10:25:29 CST 2019
     */
    public void setOrderStatus(Short orderStatus) {
        this.orderStatus = orderStatus;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.orderType
     *
     * @return the value of order_info.orderType
     *
     * @mbg.generated Sat Apr 20 10:25:29 CST 2019
     */
    public Byte getOrderType() {
        return orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.orderType
     *
     * @param orderType the value for order_info.orderType
     *
     * @mbg.generated Sat Apr 20 10:25:29 CST 2019
     */
    public void setOrderType(Byte orderType) {
        this.orderType = orderType;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.orderFrom
     *
     * @return the value of order_info.orderFrom
     *
     * @mbg.generated Sat Apr 20 10:25:29 CST 2019
     */
    public Byte getOrderFrom() {
        return orderFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.orderFrom
     *
     * @param orderFrom the value for order_info.orderFrom
     *
     * @mbg.generated Sat Apr 20 10:25:29 CST 2019
     */
    public void setOrderFrom(Byte orderFrom) {
        this.orderFrom = orderFrom;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.pOrderId
     *
     * @return the value of order_info.pOrderId
     *
     * @mbg.generated Sat Apr 20 10:25:29 CST 2019
     */
    public String getpOrderId() {
        return pOrderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.pOrderId
     *
     * @param pOrderId the value for order_info.pOrderId
     *
     * @mbg.generated Sat Apr 20 10:25:29 CST 2019
     */
    public void setpOrderId(String pOrderId) {
        this.pOrderId = pOrderId == null ? null : pOrderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.buyerId
     *
     * @return the value of order_info.buyerId
     *
     * @mbg.generated Sat Apr 20 10:25:29 CST 2019
     */
    public Integer getBuyerId() {
        return buyerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.buyerId
     *
     * @param buyerId the value for order_info.buyerId
     *
     * @mbg.generated Sat Apr 20 10:25:29 CST 2019
     */
    public void setBuyerId(Integer buyerId) {
        this.buyerId = buyerId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.consignee
     *
     * @return the value of order_info.consignee
     *
     * @mbg.generated Sat Apr 20 10:25:29 CST 2019
     */
    public String getConsignee() {
        return consignee;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.consignee
     *
     * @param consignee the value for order_info.consignee
     *
     * @mbg.generated Sat Apr 20 10:25:29 CST 2019
     */
    public void setConsignee(String consignee) {
        this.consignee = consignee == null ? null : consignee.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.province
     *
     * @return the value of order_info.province
     *
     * @mbg.generated Sat Apr 20 10:25:29 CST 2019
     */
    public Integer getProvince() {
        return province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.province
     *
     * @param province the value for order_info.province
     *
     * @mbg.generated Sat Apr 20 10:25:29 CST 2019
     */
    public void setProvince(Integer province) {
        this.province = province;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.city
     *
     * @return the value of order_info.city
     *
     * @mbg.generated Sat Apr 20 10:25:29 CST 2019
     */
    public Integer getCity() {
        return city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.city
     *
     * @param city the value for order_info.city
     *
     * @mbg.generated Sat Apr 20 10:25:29 CST 2019
     */
    public void setCity(Integer city) {
        this.city = city;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.district
     *
     * @return the value of order_info.district
     *
     * @mbg.generated Sat Apr 20 10:25:29 CST 2019
     */
    public Integer getDistrict() {
        return district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.district
     *
     * @param district the value for order_info.district
     *
     * @mbg.generated Sat Apr 20 10:25:29 CST 2019
     */
    public void setDistrict(Integer district) {
        this.district = district;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.address
     *
     * @return the value of order_info.address
     *
     * @mbg.generated Sat Apr 20 10:25:29 CST 2019
     */
    public String getAddress() {
        return address;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.address
     *
     * @param address the value for order_info.address
     *
     * @mbg.generated Sat Apr 20 10:25:29 CST 2019
     */
    public void setAddress(String address) {
        this.address = address == null ? null : address.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.tel
     *
     * @return the value of order_info.tel
     *
     * @mbg.generated Sat Apr 20 10:25:29 CST 2019
     */
    public String getTel() {
        return tel;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.tel
     *
     * @param tel the value for order_info.tel
     *
     * @mbg.generated Sat Apr 20 10:25:29 CST 2019
     */
    public void setTel(String tel) {
        this.tel = tel == null ? null : tel.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.createTime
     *
     * @return the value of order_info.createTime
     *
     * @mbg.generated Sat Apr 20 10:25:29 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.createTime
     *
     * @param createTime the value for order_info.createTime
     *
     * @mbg.generated Sat Apr 20 10:25:29 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_info.updateTime
     *
     * @return the value of order_info.updateTime
     *
     * @mbg.generated Sat Apr 20 10:25:29 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_info.updateTime
     *
     * @param updateTime the value for order_info.updateTime
     *
     * @mbg.generated Sat Apr 20 10:25:29 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}