package com.benxiaopao.provider.dao.model;

import java.math.BigDecimal;
import java.util.Date;

public class OrderItem {
    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_item.itemId
     *
     * @mbg.generated Sat Apr 20 10:25:51 CST 2019
     */
    private String itemId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_item.orderId
     *
     * @mbg.generated Sat Apr 20 10:25:51 CST 2019
     */
    private String orderId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_item.productId
     *
     * @mbg.generated Sat Apr 20 10:25:51 CST 2019
     */
    private String productId;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_item.productName
     *
     * @mbg.generated Sat Apr 20 10:25:51 CST 2019
     */
    private String productName;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_item.originPrice
     *
     * @mbg.generated Sat Apr 20 10:25:51 CST 2019
     */
    private BigDecimal originPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_item.shopPrice
     *
     * @mbg.generated Sat Apr 20 10:25:51 CST 2019
     */
    private BigDecimal shopPrice;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_item.productCount
     *
     * @mbg.generated Sat Apr 20 10:25:51 CST 2019
     */
    private Integer productCount;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_item.productIcon
     *
     * @mbg.generated Sat Apr 20 10:25:51 CST 2019
     */
    private String productIcon;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_item.createTime
     *
     * @mbg.generated Sat Apr 20 10:25:51 CST 2019
     */
    private Date createTime;

    /**
     *
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database column order_item.updateTime
     *
     * @mbg.generated Sat Apr 20 10:25:51 CST 2019
     */
    private Date updateTime;

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.itemId
     *
     * @return the value of order_item.itemId
     *
     * @mbg.generated Sat Apr 20 10:25:51 CST 2019
     */
    public String getItemId() {
        return itemId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.itemId
     *
     * @param itemId the value for order_item.itemId
     *
     * @mbg.generated Sat Apr 20 10:25:51 CST 2019
     */
    public void setItemId(String itemId) {
        this.itemId = itemId == null ? null : itemId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.orderId
     *
     * @return the value of order_item.orderId
     *
     * @mbg.generated Sat Apr 20 10:25:51 CST 2019
     */
    public String getOrderId() {
        return orderId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.orderId
     *
     * @param orderId the value for order_item.orderId
     *
     * @mbg.generated Sat Apr 20 10:25:51 CST 2019
     */
    public void setOrderId(String orderId) {
        this.orderId = orderId == null ? null : orderId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.productId
     *
     * @return the value of order_item.productId
     *
     * @mbg.generated Sat Apr 20 10:25:51 CST 2019
     */
    public String getProductId() {
        return productId;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.productId
     *
     * @param productId the value for order_item.productId
     *
     * @mbg.generated Sat Apr 20 10:25:51 CST 2019
     */
    public void setProductId(String productId) {
        this.productId = productId == null ? null : productId.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.productName
     *
     * @return the value of order_item.productName
     *
     * @mbg.generated Sat Apr 20 10:25:51 CST 2019
     */
    public String getProductName() {
        return productName;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.productName
     *
     * @param productName the value for order_item.productName
     *
     * @mbg.generated Sat Apr 20 10:25:51 CST 2019
     */
    public void setProductName(String productName) {
        this.productName = productName == null ? null : productName.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.originPrice
     *
     * @return the value of order_item.originPrice
     *
     * @mbg.generated Sat Apr 20 10:25:51 CST 2019
     */
    public BigDecimal getOriginPrice() {
        return originPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.originPrice
     *
     * @param originPrice the value for order_item.originPrice
     *
     * @mbg.generated Sat Apr 20 10:25:51 CST 2019
     */
    public void setOriginPrice(BigDecimal originPrice) {
        this.originPrice = originPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.shopPrice
     *
     * @return the value of order_item.shopPrice
     *
     * @mbg.generated Sat Apr 20 10:25:51 CST 2019
     */
    public BigDecimal getShopPrice() {
        return shopPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.shopPrice
     *
     * @param shopPrice the value for order_item.shopPrice
     *
     * @mbg.generated Sat Apr 20 10:25:51 CST 2019
     */
    public void setShopPrice(BigDecimal shopPrice) {
        this.shopPrice = shopPrice;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.productCount
     *
     * @return the value of order_item.productCount
     *
     * @mbg.generated Sat Apr 20 10:25:51 CST 2019
     */
    public Integer getProductCount() {
        return productCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.productCount
     *
     * @param productCount the value for order_item.productCount
     *
     * @mbg.generated Sat Apr 20 10:25:51 CST 2019
     */
    public void setProductCount(Integer productCount) {
        this.productCount = productCount;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.productIcon
     *
     * @return the value of order_item.productIcon
     *
     * @mbg.generated Sat Apr 20 10:25:51 CST 2019
     */
    public String getProductIcon() {
        return productIcon;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.productIcon
     *
     * @param productIcon the value for order_item.productIcon
     *
     * @mbg.generated Sat Apr 20 10:25:51 CST 2019
     */
    public void setProductIcon(String productIcon) {
        this.productIcon = productIcon == null ? null : productIcon.trim();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.createTime
     *
     * @return the value of order_item.createTime
     *
     * @mbg.generated Sat Apr 20 10:25:51 CST 2019
     */
    public Date getCreateTime() {
        return createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.createTime
     *
     * @param createTime the value for order_item.createTime
     *
     * @mbg.generated Sat Apr 20 10:25:51 CST 2019
     */
    public void setCreateTime(Date createTime) {
        this.createTime = createTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method returns the value of the database column order_item.updateTime
     *
     * @return the value of order_item.updateTime
     *
     * @mbg.generated Sat Apr 20 10:25:51 CST 2019
     */
    public Date getUpdateTime() {
        return updateTime;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method sets the value of the database column order_item.updateTime
     *
     * @param updateTime the value for order_item.updateTime
     *
     * @mbg.generated Sat Apr 20 10:25:51 CST 2019
     */
    public void setUpdateTime(Date updateTime) {
        this.updateTime = updateTime;
    }
}