package com.benxiaopao.provider.dao.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UserLoginFailureExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_login_failure
     *
     * @mbg.generated Sun May 05 00:45:08 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_login_failure
     *
     * @mbg.generated Sun May 05 00:45:08 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_login_failure
     *
     * @mbg.generated Sun May 05 00:45:08 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login_failure
     *
     * @mbg.generated Sun May 05 00:45:08 CST 2019
     */
    public UserLoginFailureExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login_failure
     *
     * @mbg.generated Sun May 05 00:45:08 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login_failure
     *
     * @mbg.generated Sun May 05 00:45:08 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login_failure
     *
     * @mbg.generated Sun May 05 00:45:08 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login_failure
     *
     * @mbg.generated Sun May 05 00:45:08 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login_failure
     *
     * @mbg.generated Sun May 05 00:45:08 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login_failure
     *
     * @mbg.generated Sun May 05 00:45:08 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login_failure
     *
     * @mbg.generated Sun May 05 00:45:08 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login_failure
     *
     * @mbg.generated Sun May 05 00:45:08 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login_failure
     *
     * @mbg.generated Sun May 05 00:45:08 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_login_failure
     *
     * @mbg.generated Sun May 05 00:45:08 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_login_failure
     *
     * @mbg.generated Sun May 05 00:45:08 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUserIdIsNull() {
            addCriterion("userId is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("userId is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Integer value) {
            addCriterion("userId =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Integer value) {
            addCriterion("userId <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Integer value) {
            addCriterion("userId >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("userId >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Integer value) {
            addCriterion("userId <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("userId <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Integer> values) {
            addCriterion("userId in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Integer> values) {
            addCriterion("userId not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Integer value1, Integer value2) {
            addCriterion("userId between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("userId not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andAttemptTimesIsNull() {
            addCriterion("attemptTimes is null");
            return (Criteria) this;
        }

        public Criteria andAttemptTimesIsNotNull() {
            addCriterion("attemptTimes is not null");
            return (Criteria) this;
        }

        public Criteria andAttemptTimesEqualTo(Integer value) {
            addCriterion("attemptTimes =", value, "attemptTimes");
            return (Criteria) this;
        }

        public Criteria andAttemptTimesNotEqualTo(Integer value) {
            addCriterion("attemptTimes <>", value, "attemptTimes");
            return (Criteria) this;
        }

        public Criteria andAttemptTimesGreaterThan(Integer value) {
            addCriterion("attemptTimes >", value, "attemptTimes");
            return (Criteria) this;
        }

        public Criteria andAttemptTimesGreaterThanOrEqualTo(Integer value) {
            addCriterion("attemptTimes >=", value, "attemptTimes");
            return (Criteria) this;
        }

        public Criteria andAttemptTimesLessThan(Integer value) {
            addCriterion("attemptTimes <", value, "attemptTimes");
            return (Criteria) this;
        }

        public Criteria andAttemptTimesLessThanOrEqualTo(Integer value) {
            addCriterion("attemptTimes <=", value, "attemptTimes");
            return (Criteria) this;
        }

        public Criteria andAttemptTimesIn(List<Integer> values) {
            addCriterion("attemptTimes in", values, "attemptTimes");
            return (Criteria) this;
        }

        public Criteria andAttemptTimesNotIn(List<Integer> values) {
            addCriterion("attemptTimes not in", values, "attemptTimes");
            return (Criteria) this;
        }

        public Criteria andAttemptTimesBetween(Integer value1, Integer value2) {
            addCriterion("attemptTimes between", value1, value2, "attemptTimes");
            return (Criteria) this;
        }

        public Criteria andAttemptTimesNotBetween(Integer value1, Integer value2) {
            addCriterion("attemptTimes not between", value1, value2, "attemptTimes");
            return (Criteria) this;
        }

        public Criteria andLastAttempedIsNull() {
            addCriterion("lastAttemped is null");
            return (Criteria) this;
        }

        public Criteria andLastAttempedIsNotNull() {
            addCriterion("lastAttemped is not null");
            return (Criteria) this;
        }

        public Criteria andLastAttempedEqualTo(Date value) {
            addCriterion("lastAttemped =", value, "lastAttemped");
            return (Criteria) this;
        }

        public Criteria andLastAttempedNotEqualTo(Date value) {
            addCriterion("lastAttemped <>", value, "lastAttemped");
            return (Criteria) this;
        }

        public Criteria andLastAttempedGreaterThan(Date value) {
            addCriterion("lastAttemped >", value, "lastAttemped");
            return (Criteria) this;
        }

        public Criteria andLastAttempedGreaterThanOrEqualTo(Date value) {
            addCriterion("lastAttemped >=", value, "lastAttemped");
            return (Criteria) this;
        }

        public Criteria andLastAttempedLessThan(Date value) {
            addCriterion("lastAttemped <", value, "lastAttemped");
            return (Criteria) this;
        }

        public Criteria andLastAttempedLessThanOrEqualTo(Date value) {
            addCriterion("lastAttemped <=", value, "lastAttemped");
            return (Criteria) this;
        }

        public Criteria andLastAttempedIn(List<Date> values) {
            addCriterion("lastAttemped in", values, "lastAttemped");
            return (Criteria) this;
        }

        public Criteria andLastAttempedNotIn(List<Date> values) {
            addCriterion("lastAttemped not in", values, "lastAttemped");
            return (Criteria) this;
        }

        public Criteria andLastAttempedBetween(Date value1, Date value2) {
            addCriterion("lastAttemped between", value1, value2, "lastAttemped");
            return (Criteria) this;
        }

        public Criteria andLastAttempedNotBetween(Date value1, Date value2) {
            addCriterion("lastAttemped not between", value1, value2, "lastAttemped");
            return (Criteria) this;
        }

        public Criteria andLastLockedIsNull() {
            addCriterion("lastLocked is null");
            return (Criteria) this;
        }

        public Criteria andLastLockedIsNotNull() {
            addCriterion("lastLocked is not null");
            return (Criteria) this;
        }

        public Criteria andLastLockedEqualTo(Date value) {
            addCriterion("lastLocked =", value, "lastLocked");
            return (Criteria) this;
        }

        public Criteria andLastLockedNotEqualTo(Date value) {
            addCriterion("lastLocked <>", value, "lastLocked");
            return (Criteria) this;
        }

        public Criteria andLastLockedGreaterThan(Date value) {
            addCriterion("lastLocked >", value, "lastLocked");
            return (Criteria) this;
        }

        public Criteria andLastLockedGreaterThanOrEqualTo(Date value) {
            addCriterion("lastLocked >=", value, "lastLocked");
            return (Criteria) this;
        }

        public Criteria andLastLockedLessThan(Date value) {
            addCriterion("lastLocked <", value, "lastLocked");
            return (Criteria) this;
        }

        public Criteria andLastLockedLessThanOrEqualTo(Date value) {
            addCriterion("lastLocked <=", value, "lastLocked");
            return (Criteria) this;
        }

        public Criteria andLastLockedIn(List<Date> values) {
            addCriterion("lastLocked in", values, "lastLocked");
            return (Criteria) this;
        }

        public Criteria andLastLockedNotIn(List<Date> values) {
            addCriterion("lastLocked not in", values, "lastLocked");
            return (Criteria) this;
        }

        public Criteria andLastLockedBetween(Date value1, Date value2) {
            addCriterion("lastLocked between", value1, value2, "lastLocked");
            return (Criteria) this;
        }

        public Criteria andLastLockedNotBetween(Date value1, Date value2) {
            addCriterion("lastLocked not between", value1, value2, "lastLocked");
            return (Criteria) this;
        }

        public Criteria andLastLoginIPIsNull() {
            addCriterion("lastLoginIP is null");
            return (Criteria) this;
        }

        public Criteria andLastLoginIPIsNotNull() {
            addCriterion("lastLoginIP is not null");
            return (Criteria) this;
        }

        public Criteria andLastLoginIPEqualTo(Long value) {
            addCriterion("lastLoginIP =", value, "lastLoginIP");
            return (Criteria) this;
        }

        public Criteria andLastLoginIPNotEqualTo(Long value) {
            addCriterion("lastLoginIP <>", value, "lastLoginIP");
            return (Criteria) this;
        }

        public Criteria andLastLoginIPGreaterThan(Long value) {
            addCriterion("lastLoginIP >", value, "lastLoginIP");
            return (Criteria) this;
        }

        public Criteria andLastLoginIPGreaterThanOrEqualTo(Long value) {
            addCriterion("lastLoginIP >=", value, "lastLoginIP");
            return (Criteria) this;
        }

        public Criteria andLastLoginIPLessThan(Long value) {
            addCriterion("lastLoginIP <", value, "lastLoginIP");
            return (Criteria) this;
        }

        public Criteria andLastLoginIPLessThanOrEqualTo(Long value) {
            addCriterion("lastLoginIP <=", value, "lastLoginIP");
            return (Criteria) this;
        }

        public Criteria andLastLoginIPIn(List<Long> values) {
            addCriterion("lastLoginIP in", values, "lastLoginIP");
            return (Criteria) this;
        }

        public Criteria andLastLoginIPNotIn(List<Long> values) {
            addCriterion("lastLoginIP not in", values, "lastLoginIP");
            return (Criteria) this;
        }

        public Criteria andLastLoginIPBetween(Long value1, Long value2) {
            addCriterion("lastLoginIP between", value1, value2, "lastLoginIP");
            return (Criteria) this;
        }

        public Criteria andLastLoginIPNotBetween(Long value1, Long value2) {
            addCriterion("lastLoginIP not between", value1, value2, "lastLoginIP");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_login_failure
     *
     * @mbg.generated do_not_delete_during_merge Sun May 05 00:45:08 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_login_failure
     *
     * @mbg.generated Sun May 05 00:45:08 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}