package com.benxiaopao.provider.dao.model;

import java.util.ArrayList;
import java.util.Date;
import java.util.List;

public class UserExample {
    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_info
     *
     * @mbg.generated Sat Apr 20 10:26:44 CST 2019
     */
    protected String orderByClause;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_info
     *
     * @mbg.generated Sat Apr 20 10:26:44 CST 2019
     */
    protected boolean distinct;

    /**
     * This field was generated by MyBatis Generator.
     * This field corresponds to the database table user_info
     *
     * @mbg.generated Sat Apr 20 10:26:44 CST 2019
     */
    protected List<Criteria> oredCriteria;

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Sat Apr 20 10:26:44 CST 2019
     */
    public UserExample() {
        oredCriteria = new ArrayList<Criteria>();
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Sat Apr 20 10:26:44 CST 2019
     */
    public void setOrderByClause(String orderByClause) {
        this.orderByClause = orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Sat Apr 20 10:26:44 CST 2019
     */
    public String getOrderByClause() {
        return orderByClause;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Sat Apr 20 10:26:44 CST 2019
     */
    public void setDistinct(boolean distinct) {
        this.distinct = distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Sat Apr 20 10:26:44 CST 2019
     */
    public boolean isDistinct() {
        return distinct;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Sat Apr 20 10:26:44 CST 2019
     */
    public List<Criteria> getOredCriteria() {
        return oredCriteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Sat Apr 20 10:26:44 CST 2019
     */
    public void or(Criteria criteria) {
        oredCriteria.add(criteria);
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Sat Apr 20 10:26:44 CST 2019
     */
    public Criteria or() {
        Criteria criteria = createCriteriaInternal();
        oredCriteria.add(criteria);
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Sat Apr 20 10:26:44 CST 2019
     */
    public Criteria createCriteria() {
        Criteria criteria = createCriteriaInternal();
        if (oredCriteria.size() == 0) {
            oredCriteria.add(criteria);
        }
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Sat Apr 20 10:26:44 CST 2019
     */
    protected Criteria createCriteriaInternal() {
        Criteria criteria = new Criteria();
        return criteria;
    }

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table user_info
     *
     * @mbg.generated Sat Apr 20 10:26:44 CST 2019
     */
    public void clear() {
        oredCriteria.clear();
        orderByClause = null;
        distinct = false;
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_info
     *
     * @mbg.generated Sat Apr 20 10:26:44 CST 2019
     */
    protected abstract static class GeneratedCriteria {
        protected List<Criterion> criteria;

        protected GeneratedCriteria() {
            super();
            criteria = new ArrayList<Criterion>();
        }

        public boolean isValid() {
            return criteria.size() > 0;
        }

        public List<Criterion> getAllCriteria() {
            return criteria;
        }

        public List<Criterion> getCriteria() {
            return criteria;
        }

        protected void addCriterion(String condition) {
            if (condition == null) {
                throw new RuntimeException("Value for condition cannot be null");
            }
            criteria.add(new Criterion(condition));
        }

        protected void addCriterion(String condition, Object value, String property) {
            if (value == null) {
                throw new RuntimeException("Value for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value));
        }

        protected void addCriterion(String condition, Object value1, Object value2, String property) {
            if (value1 == null || value2 == null) {
                throw new RuntimeException("Between values for " + property + " cannot be null");
            }
            criteria.add(new Criterion(condition, value1, value2));
        }

        public Criteria andUserIdIsNull() {
            addCriterion("userId is null");
            return (Criteria) this;
        }

        public Criteria andUserIdIsNotNull() {
            addCriterion("userId is not null");
            return (Criteria) this;
        }

        public Criteria andUserIdEqualTo(Integer value) {
            addCriterion("userId =", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotEqualTo(Integer value) {
            addCriterion("userId <>", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThan(Integer value) {
            addCriterion("userId >", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdGreaterThanOrEqualTo(Integer value) {
            addCriterion("userId >=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThan(Integer value) {
            addCriterion("userId <", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdLessThanOrEqualTo(Integer value) {
            addCriterion("userId <=", value, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdIn(List<Integer> values) {
            addCriterion("userId in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotIn(List<Integer> values) {
            addCriterion("userId not in", values, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdBetween(Integer value1, Integer value2) {
            addCriterion("userId between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andUserIdNotBetween(Integer value1, Integer value2) {
            addCriterion("userId not between", value1, value2, "userId");
            return (Criteria) this;
        }

        public Criteria andEmailIsNull() {
            addCriterion("email is null");
            return (Criteria) this;
        }

        public Criteria andEmailIsNotNull() {
            addCriterion("email is not null");
            return (Criteria) this;
        }

        public Criteria andEmailEqualTo(String value) {
            addCriterion("email =", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotEqualTo(String value) {
            addCriterion("email <>", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThan(String value) {
            addCriterion("email >", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailGreaterThanOrEqualTo(String value) {
            addCriterion("email >=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThan(String value) {
            addCriterion("email <", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLessThanOrEqualTo(String value) {
            addCriterion("email <=", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailLike(String value) {
            addCriterion("email like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotLike(String value) {
            addCriterion("email not like", value, "email");
            return (Criteria) this;
        }

        public Criteria andEmailIn(List<String> values) {
            addCriterion("email in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotIn(List<String> values) {
            addCriterion("email not in", values, "email");
            return (Criteria) this;
        }

        public Criteria andEmailBetween(String value1, String value2) {
            addCriterion("email between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andEmailNotBetween(String value1, String value2) {
            addCriterion("email not between", value1, value2, "email");
            return (Criteria) this;
        }

        public Criteria andNickNameIsNull() {
            addCriterion("nickName is null");
            return (Criteria) this;
        }

        public Criteria andNickNameIsNotNull() {
            addCriterion("nickName is not null");
            return (Criteria) this;
        }

        public Criteria andNickNameEqualTo(String value) {
            addCriterion("nickName =", value, "nickName");
            return (Criteria) this;
        }

        public Criteria andNickNameNotEqualTo(String value) {
            addCriterion("nickName <>", value, "nickName");
            return (Criteria) this;
        }

        public Criteria andNickNameGreaterThan(String value) {
            addCriterion("nickName >", value, "nickName");
            return (Criteria) this;
        }

        public Criteria andNickNameGreaterThanOrEqualTo(String value) {
            addCriterion("nickName >=", value, "nickName");
            return (Criteria) this;
        }

        public Criteria andNickNameLessThan(String value) {
            addCriterion("nickName <", value, "nickName");
            return (Criteria) this;
        }

        public Criteria andNickNameLessThanOrEqualTo(String value) {
            addCriterion("nickName <=", value, "nickName");
            return (Criteria) this;
        }

        public Criteria andNickNameLike(String value) {
            addCriterion("nickName like", value, "nickName");
            return (Criteria) this;
        }

        public Criteria andNickNameNotLike(String value) {
            addCriterion("nickName not like", value, "nickName");
            return (Criteria) this;
        }

        public Criteria andNickNameIn(List<String> values) {
            addCriterion("nickName in", values, "nickName");
            return (Criteria) this;
        }

        public Criteria andNickNameNotIn(List<String> values) {
            addCriterion("nickName not in", values, "nickName");
            return (Criteria) this;
        }

        public Criteria andNickNameBetween(String value1, String value2) {
            addCriterion("nickName between", value1, value2, "nickName");
            return (Criteria) this;
        }

        public Criteria andNickNameNotBetween(String value1, String value2) {
            addCriterion("nickName not between", value1, value2, "nickName");
            return (Criteria) this;
        }

        public Criteria andRealNameIsNull() {
            addCriterion("realName is null");
            return (Criteria) this;
        }

        public Criteria andRealNameIsNotNull() {
            addCriterion("realName is not null");
            return (Criteria) this;
        }

        public Criteria andRealNameEqualTo(String value) {
            addCriterion("realName =", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameNotEqualTo(String value) {
            addCriterion("realName <>", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameGreaterThan(String value) {
            addCriterion("realName >", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameGreaterThanOrEqualTo(String value) {
            addCriterion("realName >=", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameLessThan(String value) {
            addCriterion("realName <", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameLessThanOrEqualTo(String value) {
            addCriterion("realName <=", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameLike(String value) {
            addCriterion("realName like", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameNotLike(String value) {
            addCriterion("realName not like", value, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameIn(List<String> values) {
            addCriterion("realName in", values, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameNotIn(List<String> values) {
            addCriterion("realName not in", values, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameBetween(String value1, String value2) {
            addCriterion("realName between", value1, value2, "realName");
            return (Criteria) this;
        }

        public Criteria andRealNameNotBetween(String value1, String value2) {
            addCriterion("realName not between", value1, value2, "realName");
            return (Criteria) this;
        }

        public Criteria andDisplayNameIsNull() {
            addCriterion("displayName is null");
            return (Criteria) this;
        }

        public Criteria andDisplayNameIsNotNull() {
            addCriterion("displayName is not null");
            return (Criteria) this;
        }

        public Criteria andDisplayNameEqualTo(String value) {
            addCriterion("displayName =", value, "displayName");
            return (Criteria) this;
        }

        public Criteria andDisplayNameNotEqualTo(String value) {
            addCriterion("displayName <>", value, "displayName");
            return (Criteria) this;
        }

        public Criteria andDisplayNameGreaterThan(String value) {
            addCriterion("displayName >", value, "displayName");
            return (Criteria) this;
        }

        public Criteria andDisplayNameGreaterThanOrEqualTo(String value) {
            addCriterion("displayName >=", value, "displayName");
            return (Criteria) this;
        }

        public Criteria andDisplayNameLessThan(String value) {
            addCriterion("displayName <", value, "displayName");
            return (Criteria) this;
        }

        public Criteria andDisplayNameLessThanOrEqualTo(String value) {
            addCriterion("displayName <=", value, "displayName");
            return (Criteria) this;
        }

        public Criteria andDisplayNameLike(String value) {
            addCriterion("displayName like", value, "displayName");
            return (Criteria) this;
        }

        public Criteria andDisplayNameNotLike(String value) {
            addCriterion("displayName not like", value, "displayName");
            return (Criteria) this;
        }

        public Criteria andDisplayNameIn(List<String> values) {
            addCriterion("displayName in", values, "displayName");
            return (Criteria) this;
        }

        public Criteria andDisplayNameNotIn(List<String> values) {
            addCriterion("displayName not in", values, "displayName");
            return (Criteria) this;
        }

        public Criteria andDisplayNameBetween(String value1, String value2) {
            addCriterion("displayName between", value1, value2, "displayName");
            return (Criteria) this;
        }

        public Criteria andDisplayNameNotBetween(String value1, String value2) {
            addCriterion("displayName not between", value1, value2, "displayName");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNull() {
            addCriterion("password is null");
            return (Criteria) this;
        }

        public Criteria andPasswordIsNotNull() {
            addCriterion("password is not null");
            return (Criteria) this;
        }

        public Criteria andPasswordEqualTo(String value) {
            addCriterion("password =", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotEqualTo(String value) {
            addCriterion("password <>", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThan(String value) {
            addCriterion("password >", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordGreaterThanOrEqualTo(String value) {
            addCriterion("password >=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThan(String value) {
            addCriterion("password <", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLessThanOrEqualTo(String value) {
            addCriterion("password <=", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordLike(String value) {
            addCriterion("password like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotLike(String value) {
            addCriterion("password not like", value, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordIn(List<String> values) {
            addCriterion("password in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotIn(List<String> values) {
            addCriterion("password not in", values, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordBetween(String value1, String value2) {
            addCriterion("password between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andPasswordNotBetween(String value1, String value2) {
            addCriterion("password not between", value1, value2, "password");
            return (Criteria) this;
        }

        public Criteria andMobileIsNull() {
            addCriterion("mobile is null");
            return (Criteria) this;
        }

        public Criteria andMobileIsNotNull() {
            addCriterion("mobile is not null");
            return (Criteria) this;
        }

        public Criteria andMobileEqualTo(String value) {
            addCriterion("mobile =", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotEqualTo(String value) {
            addCriterion("mobile <>", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileGreaterThan(String value) {
            addCriterion("mobile >", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileGreaterThanOrEqualTo(String value) {
            addCriterion("mobile >=", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileLessThan(String value) {
            addCriterion("mobile <", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileLessThanOrEqualTo(String value) {
            addCriterion("mobile <=", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileLike(String value) {
            addCriterion("mobile like", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotLike(String value) {
            addCriterion("mobile not like", value, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileIn(List<String> values) {
            addCriterion("mobile in", values, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotIn(List<String> values) {
            addCriterion("mobile not in", values, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileBetween(String value1, String value2) {
            addCriterion("mobile between", value1, value2, "mobile");
            return (Criteria) this;
        }

        public Criteria andMobileNotBetween(String value1, String value2) {
            addCriterion("mobile not between", value1, value2, "mobile");
            return (Criteria) this;
        }

        public Criteria andCityIsNull() {
            addCriterion("city is null");
            return (Criteria) this;
        }

        public Criteria andCityIsNotNull() {
            addCriterion("city is not null");
            return (Criteria) this;
        }

        public Criteria andCityEqualTo(String value) {
            addCriterion("city =", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotEqualTo(String value) {
            addCriterion("city <>", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityGreaterThan(String value) {
            addCriterion("city >", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityGreaterThanOrEqualTo(String value) {
            addCriterion("city >=", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLessThan(String value) {
            addCriterion("city <", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLessThanOrEqualTo(String value) {
            addCriterion("city <=", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityLike(String value) {
            addCriterion("city like", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotLike(String value) {
            addCriterion("city not like", value, "city");
            return (Criteria) this;
        }

        public Criteria andCityIn(List<String> values) {
            addCriterion("city in", values, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotIn(List<String> values) {
            addCriterion("city not in", values, "city");
            return (Criteria) this;
        }

        public Criteria andCityBetween(String value1, String value2) {
            addCriterion("city between", value1, value2, "city");
            return (Criteria) this;
        }

        public Criteria andCityNotBetween(String value1, String value2) {
            addCriterion("city not between", value1, value2, "city");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeIsNull() {
            addCriterion("registerTime is null");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeIsNotNull() {
            addCriterion("registerTime is not null");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeEqualTo(Date value) {
            addCriterion("registerTime =", value, "registerTime");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeNotEqualTo(Date value) {
            addCriterion("registerTime <>", value, "registerTime");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeGreaterThan(Date value) {
            addCriterion("registerTime >", value, "registerTime");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("registerTime >=", value, "registerTime");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeLessThan(Date value) {
            addCriterion("registerTime <", value, "registerTime");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeLessThanOrEqualTo(Date value) {
            addCriterion("registerTime <=", value, "registerTime");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeIn(List<Date> values) {
            addCriterion("registerTime in", values, "registerTime");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeNotIn(List<Date> values) {
            addCriterion("registerTime not in", values, "registerTime");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeBetween(Date value1, Date value2) {
            addCriterion("registerTime between", value1, value2, "registerTime");
            return (Criteria) this;
        }

        public Criteria andRegisterTimeNotBetween(Date value1, Date value2) {
            addCriterion("registerTime not between", value1, value2, "registerTime");
            return (Criteria) this;
        }

        public Criteria andActiveTimeIsNull() {
            addCriterion("activeTime is null");
            return (Criteria) this;
        }

        public Criteria andActiveTimeIsNotNull() {
            addCriterion("activeTime is not null");
            return (Criteria) this;
        }

        public Criteria andActiveTimeEqualTo(Date value) {
            addCriterion("activeTime =", value, "activeTime");
            return (Criteria) this;
        }

        public Criteria andActiveTimeNotEqualTo(Date value) {
            addCriterion("activeTime <>", value, "activeTime");
            return (Criteria) this;
        }

        public Criteria andActiveTimeGreaterThan(Date value) {
            addCriterion("activeTime >", value, "activeTime");
            return (Criteria) this;
        }

        public Criteria andActiveTimeGreaterThanOrEqualTo(Date value) {
            addCriterion("activeTime >=", value, "activeTime");
            return (Criteria) this;
        }

        public Criteria andActiveTimeLessThan(Date value) {
            addCriterion("activeTime <", value, "activeTime");
            return (Criteria) this;
        }

        public Criteria andActiveTimeLessThanOrEqualTo(Date value) {
            addCriterion("activeTime <=", value, "activeTime");
            return (Criteria) this;
        }

        public Criteria andActiveTimeIn(List<Date> values) {
            addCriterion("activeTime in", values, "activeTime");
            return (Criteria) this;
        }

        public Criteria andActiveTimeNotIn(List<Date> values) {
            addCriterion("activeTime not in", values, "activeTime");
            return (Criteria) this;
        }

        public Criteria andActiveTimeBetween(Date value1, Date value2) {
            addCriterion("activeTime between", value1, value2, "activeTime");
            return (Criteria) this;
        }

        public Criteria andActiveTimeNotBetween(Date value1, Date value2) {
            addCriterion("activeTime not between", value1, value2, "activeTime");
            return (Criteria) this;
        }

        public Criteria andStatusIsNull() {
            addCriterion("status is null");
            return (Criteria) this;
        }

        public Criteria andStatusIsNotNull() {
            addCriterion("status is not null");
            return (Criteria) this;
        }

        public Criteria andStatusEqualTo(Short value) {
            addCriterion("status =", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotEqualTo(Short value) {
            addCriterion("status <>", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThan(Short value) {
            addCriterion("status >", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusGreaterThanOrEqualTo(Short value) {
            addCriterion("status >=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThan(Short value) {
            addCriterion("status <", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusLessThanOrEqualTo(Short value) {
            addCriterion("status <=", value, "status");
            return (Criteria) this;
        }

        public Criteria andStatusIn(List<Short> values) {
            addCriterion("status in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotIn(List<Short> values) {
            addCriterion("status not in", values, "status");
            return (Criteria) this;
        }

        public Criteria andStatusBetween(Short value1, Short value2) {
            addCriterion("status between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andStatusNotBetween(Short value1, Short value2) {
            addCriterion("status not between", value1, value2, "status");
            return (Criteria) this;
        }

        public Criteria andForbidStatusIsNull() {
            addCriterion("forbidStatus is null");
            return (Criteria) this;
        }

        public Criteria andForbidStatusIsNotNull() {
            addCriterion("forbidStatus is not null");
            return (Criteria) this;
        }

        public Criteria andForbidStatusEqualTo(Short value) {
            addCriterion("forbidStatus =", value, "forbidStatus");
            return (Criteria) this;
        }

        public Criteria andForbidStatusNotEqualTo(Short value) {
            addCriterion("forbidStatus <>", value, "forbidStatus");
            return (Criteria) this;
        }

        public Criteria andForbidStatusGreaterThan(Short value) {
            addCriterion("forbidStatus >", value, "forbidStatus");
            return (Criteria) this;
        }

        public Criteria andForbidStatusGreaterThanOrEqualTo(Short value) {
            addCriterion("forbidStatus >=", value, "forbidStatus");
            return (Criteria) this;
        }

        public Criteria andForbidStatusLessThan(Short value) {
            addCriterion("forbidStatus <", value, "forbidStatus");
            return (Criteria) this;
        }

        public Criteria andForbidStatusLessThanOrEqualTo(Short value) {
            addCriterion("forbidStatus <=", value, "forbidStatus");
            return (Criteria) this;
        }

        public Criteria andForbidStatusIn(List<Short> values) {
            addCriterion("forbidStatus in", values, "forbidStatus");
            return (Criteria) this;
        }

        public Criteria andForbidStatusNotIn(List<Short> values) {
            addCriterion("forbidStatus not in", values, "forbidStatus");
            return (Criteria) this;
        }

        public Criteria andForbidStatusBetween(Short value1, Short value2) {
            addCriterion("forbidStatus between", value1, value2, "forbidStatus");
            return (Criteria) this;
        }

        public Criteria andForbidStatusNotBetween(Short value1, Short value2) {
            addCriterion("forbidStatus not between", value1, value2, "forbidStatus");
            return (Criteria) this;
        }

        public Criteria andSecurityLevelIsNull() {
            addCriterion("securityLevel is null");
            return (Criteria) this;
        }

        public Criteria andSecurityLevelIsNotNull() {
            addCriterion("securityLevel is not null");
            return (Criteria) this;
        }

        public Criteria andSecurityLevelEqualTo(Short value) {
            addCriterion("securityLevel =", value, "securityLevel");
            return (Criteria) this;
        }

        public Criteria andSecurityLevelNotEqualTo(Short value) {
            addCriterion("securityLevel <>", value, "securityLevel");
            return (Criteria) this;
        }

        public Criteria andSecurityLevelGreaterThan(Short value) {
            addCriterion("securityLevel >", value, "securityLevel");
            return (Criteria) this;
        }

        public Criteria andSecurityLevelGreaterThanOrEqualTo(Short value) {
            addCriterion("securityLevel >=", value, "securityLevel");
            return (Criteria) this;
        }

        public Criteria andSecurityLevelLessThan(Short value) {
            addCriterion("securityLevel <", value, "securityLevel");
            return (Criteria) this;
        }

        public Criteria andSecurityLevelLessThanOrEqualTo(Short value) {
            addCriterion("securityLevel <=", value, "securityLevel");
            return (Criteria) this;
        }

        public Criteria andSecurityLevelIn(List<Short> values) {
            addCriterion("securityLevel in", values, "securityLevel");
            return (Criteria) this;
        }

        public Criteria andSecurityLevelNotIn(List<Short> values) {
            addCriterion("securityLevel not in", values, "securityLevel");
            return (Criteria) this;
        }

        public Criteria andSecurityLevelBetween(Short value1, Short value2) {
            addCriterion("securityLevel between", value1, value2, "securityLevel");
            return (Criteria) this;
        }

        public Criteria andSecurityLevelNotBetween(Short value1, Short value2) {
            addCriterion("securityLevel not between", value1, value2, "securityLevel");
            return (Criteria) this;
        }

        public Criteria andWeiboUIdIsNull() {
            addCriterion("weiboUId is null");
            return (Criteria) this;
        }

        public Criteria andWeiboUIdIsNotNull() {
            addCriterion("weiboUId is not null");
            return (Criteria) this;
        }

        public Criteria andWeiboUIdEqualTo(String value) {
            addCriterion("weiboUId =", value, "weiboUId");
            return (Criteria) this;
        }

        public Criteria andWeiboUIdNotEqualTo(String value) {
            addCriterion("weiboUId <>", value, "weiboUId");
            return (Criteria) this;
        }

        public Criteria andWeiboUIdGreaterThan(String value) {
            addCriterion("weiboUId >", value, "weiboUId");
            return (Criteria) this;
        }

        public Criteria andWeiboUIdGreaterThanOrEqualTo(String value) {
            addCriterion("weiboUId >=", value, "weiboUId");
            return (Criteria) this;
        }

        public Criteria andWeiboUIdLessThan(String value) {
            addCriterion("weiboUId <", value, "weiboUId");
            return (Criteria) this;
        }

        public Criteria andWeiboUIdLessThanOrEqualTo(String value) {
            addCriterion("weiboUId <=", value, "weiboUId");
            return (Criteria) this;
        }

        public Criteria andWeiboUIdLike(String value) {
            addCriterion("weiboUId like", value, "weiboUId");
            return (Criteria) this;
        }

        public Criteria andWeiboUIdNotLike(String value) {
            addCriterion("weiboUId not like", value, "weiboUId");
            return (Criteria) this;
        }

        public Criteria andWeiboUIdIn(List<String> values) {
            addCriterion("weiboUId in", values, "weiboUId");
            return (Criteria) this;
        }

        public Criteria andWeiboUIdNotIn(List<String> values) {
            addCriterion("weiboUId not in", values, "weiboUId");
            return (Criteria) this;
        }

        public Criteria andWeiboUIdBetween(String value1, String value2) {
            addCriterion("weiboUId between", value1, value2, "weiboUId");
            return (Criteria) this;
        }

        public Criteria andWeiboUIdNotBetween(String value1, String value2) {
            addCriterion("weiboUId not between", value1, value2, "weiboUId");
            return (Criteria) this;
        }

        public Criteria andWeiboAccessTokenIsNull() {
            addCriterion("weiboAccessToken is null");
            return (Criteria) this;
        }

        public Criteria andWeiboAccessTokenIsNotNull() {
            addCriterion("weiboAccessToken is not null");
            return (Criteria) this;
        }

        public Criteria andWeiboAccessTokenEqualTo(String value) {
            addCriterion("weiboAccessToken =", value, "weiboAccessToken");
            return (Criteria) this;
        }

        public Criteria andWeiboAccessTokenNotEqualTo(String value) {
            addCriterion("weiboAccessToken <>", value, "weiboAccessToken");
            return (Criteria) this;
        }

        public Criteria andWeiboAccessTokenGreaterThan(String value) {
            addCriterion("weiboAccessToken >", value, "weiboAccessToken");
            return (Criteria) this;
        }

        public Criteria andWeiboAccessTokenGreaterThanOrEqualTo(String value) {
            addCriterion("weiboAccessToken >=", value, "weiboAccessToken");
            return (Criteria) this;
        }

        public Criteria andWeiboAccessTokenLessThan(String value) {
            addCriterion("weiboAccessToken <", value, "weiboAccessToken");
            return (Criteria) this;
        }

        public Criteria andWeiboAccessTokenLessThanOrEqualTo(String value) {
            addCriterion("weiboAccessToken <=", value, "weiboAccessToken");
            return (Criteria) this;
        }

        public Criteria andWeiboAccessTokenLike(String value) {
            addCriterion("weiboAccessToken like", value, "weiboAccessToken");
            return (Criteria) this;
        }

        public Criteria andWeiboAccessTokenNotLike(String value) {
            addCriterion("weiboAccessToken not like", value, "weiboAccessToken");
            return (Criteria) this;
        }

        public Criteria andWeiboAccessTokenIn(List<String> values) {
            addCriterion("weiboAccessToken in", values, "weiboAccessToken");
            return (Criteria) this;
        }

        public Criteria andWeiboAccessTokenNotIn(List<String> values) {
            addCriterion("weiboAccessToken not in", values, "weiboAccessToken");
            return (Criteria) this;
        }

        public Criteria andWeiboAccessTokenBetween(String value1, String value2) {
            addCriterion("weiboAccessToken between", value1, value2, "weiboAccessToken");
            return (Criteria) this;
        }

        public Criteria andWeiboAccessTokenNotBetween(String value1, String value2) {
            addCriterion("weiboAccessToken not between", value1, value2, "weiboAccessToken");
            return (Criteria) this;
        }

        public Criteria andQqUIdIsNull() {
            addCriterion("qqUId is null");
            return (Criteria) this;
        }

        public Criteria andQqUIdIsNotNull() {
            addCriterion("qqUId is not null");
            return (Criteria) this;
        }

        public Criteria andQqUIdEqualTo(String value) {
            addCriterion("qqUId =", value, "qqUId");
            return (Criteria) this;
        }

        public Criteria andQqUIdNotEqualTo(String value) {
            addCriterion("qqUId <>", value, "qqUId");
            return (Criteria) this;
        }

        public Criteria andQqUIdGreaterThan(String value) {
            addCriterion("qqUId >", value, "qqUId");
            return (Criteria) this;
        }

        public Criteria andQqUIdGreaterThanOrEqualTo(String value) {
            addCriterion("qqUId >=", value, "qqUId");
            return (Criteria) this;
        }

        public Criteria andQqUIdLessThan(String value) {
            addCriterion("qqUId <", value, "qqUId");
            return (Criteria) this;
        }

        public Criteria andQqUIdLessThanOrEqualTo(String value) {
            addCriterion("qqUId <=", value, "qqUId");
            return (Criteria) this;
        }

        public Criteria andQqUIdLike(String value) {
            addCriterion("qqUId like", value, "qqUId");
            return (Criteria) this;
        }

        public Criteria andQqUIdNotLike(String value) {
            addCriterion("qqUId not like", value, "qqUId");
            return (Criteria) this;
        }

        public Criteria andQqUIdIn(List<String> values) {
            addCriterion("qqUId in", values, "qqUId");
            return (Criteria) this;
        }

        public Criteria andQqUIdNotIn(List<String> values) {
            addCriterion("qqUId not in", values, "qqUId");
            return (Criteria) this;
        }

        public Criteria andQqUIdBetween(String value1, String value2) {
            addCriterion("qqUId between", value1, value2, "qqUId");
            return (Criteria) this;
        }

        public Criteria andQqUIdNotBetween(String value1, String value2) {
            addCriterion("qqUId not between", value1, value2, "qqUId");
            return (Criteria) this;
        }

        public Criteria andQqAccessTokenIsNull() {
            addCriterion("qqAccessToken is null");
            return (Criteria) this;
        }

        public Criteria andQqAccessTokenIsNotNull() {
            addCriterion("qqAccessToken is not null");
            return (Criteria) this;
        }

        public Criteria andQqAccessTokenEqualTo(String value) {
            addCriterion("qqAccessToken =", value, "qqAccessToken");
            return (Criteria) this;
        }

        public Criteria andQqAccessTokenNotEqualTo(String value) {
            addCriterion("qqAccessToken <>", value, "qqAccessToken");
            return (Criteria) this;
        }

        public Criteria andQqAccessTokenGreaterThan(String value) {
            addCriterion("qqAccessToken >", value, "qqAccessToken");
            return (Criteria) this;
        }

        public Criteria andQqAccessTokenGreaterThanOrEqualTo(String value) {
            addCriterion("qqAccessToken >=", value, "qqAccessToken");
            return (Criteria) this;
        }

        public Criteria andQqAccessTokenLessThan(String value) {
            addCriterion("qqAccessToken <", value, "qqAccessToken");
            return (Criteria) this;
        }

        public Criteria andQqAccessTokenLessThanOrEqualTo(String value) {
            addCriterion("qqAccessToken <=", value, "qqAccessToken");
            return (Criteria) this;
        }

        public Criteria andQqAccessTokenLike(String value) {
            addCriterion("qqAccessToken like", value, "qqAccessToken");
            return (Criteria) this;
        }

        public Criteria andQqAccessTokenNotLike(String value) {
            addCriterion("qqAccessToken not like", value, "qqAccessToken");
            return (Criteria) this;
        }

        public Criteria andQqAccessTokenIn(List<String> values) {
            addCriterion("qqAccessToken in", values, "qqAccessToken");
            return (Criteria) this;
        }

        public Criteria andQqAccessTokenNotIn(List<String> values) {
            addCriterion("qqAccessToken not in", values, "qqAccessToken");
            return (Criteria) this;
        }

        public Criteria andQqAccessTokenBetween(String value1, String value2) {
            addCriterion("qqAccessToken between", value1, value2, "qqAccessToken");
            return (Criteria) this;
        }

        public Criteria andQqAccessTokenNotBetween(String value1, String value2) {
            addCriterion("qqAccessToken not between", value1, value2, "qqAccessToken");
            return (Criteria) this;
        }

        public Criteria andRegisterChannelIdIsNull() {
            addCriterion("registerChannelId is null");
            return (Criteria) this;
        }

        public Criteria andRegisterChannelIdIsNotNull() {
            addCriterion("registerChannelId is not null");
            return (Criteria) this;
        }

        public Criteria andRegisterChannelIdEqualTo(String value) {
            addCriterion("registerChannelId =", value, "registerChannelId");
            return (Criteria) this;
        }

        public Criteria andRegisterChannelIdNotEqualTo(String value) {
            addCriterion("registerChannelId <>", value, "registerChannelId");
            return (Criteria) this;
        }

        public Criteria andRegisterChannelIdGreaterThan(String value) {
            addCriterion("registerChannelId >", value, "registerChannelId");
            return (Criteria) this;
        }

        public Criteria andRegisterChannelIdGreaterThanOrEqualTo(String value) {
            addCriterion("registerChannelId >=", value, "registerChannelId");
            return (Criteria) this;
        }

        public Criteria andRegisterChannelIdLessThan(String value) {
            addCriterion("registerChannelId <", value, "registerChannelId");
            return (Criteria) this;
        }

        public Criteria andRegisterChannelIdLessThanOrEqualTo(String value) {
            addCriterion("registerChannelId <=", value, "registerChannelId");
            return (Criteria) this;
        }

        public Criteria andRegisterChannelIdLike(String value) {
            addCriterion("registerChannelId like", value, "registerChannelId");
            return (Criteria) this;
        }

        public Criteria andRegisterChannelIdNotLike(String value) {
            addCriterion("registerChannelId not like", value, "registerChannelId");
            return (Criteria) this;
        }

        public Criteria andRegisterChannelIdIn(List<String> values) {
            addCriterion("registerChannelId in", values, "registerChannelId");
            return (Criteria) this;
        }

        public Criteria andRegisterChannelIdNotIn(List<String> values) {
            addCriterion("registerChannelId not in", values, "registerChannelId");
            return (Criteria) this;
        }

        public Criteria andRegisterChannelIdBetween(String value1, String value2) {
            addCriterion("registerChannelId between", value1, value2, "registerChannelId");
            return (Criteria) this;
        }

        public Criteria andRegisterChannelIdNotBetween(String value1, String value2) {
            addCriterion("registerChannelId not between", value1, value2, "registerChannelId");
            return (Criteria) this;
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_info
     *
     * @mbg.generated do_not_delete_during_merge Sat Apr 20 10:26:44 CST 2019
     */
    public static class Criteria extends GeneratedCriteria {

        protected Criteria() {
            super();
        }
    }

    /**
     * This class was generated by MyBatis Generator.
     * This class corresponds to the database table user_info
     *
     * @mbg.generated Sat Apr 20 10:26:44 CST 2019
     */
    public static class Criterion {
        private String condition;

        private Object value;

        private Object secondValue;

        private boolean noValue;

        private boolean singleValue;

        private boolean betweenValue;

        private boolean listValue;

        private String typeHandler;

        public String getCondition() {
            return condition;
        }

        public Object getValue() {
            return value;
        }

        public Object getSecondValue() {
            return secondValue;
        }

        public boolean isNoValue() {
            return noValue;
        }

        public boolean isSingleValue() {
            return singleValue;
        }

        public boolean isBetweenValue() {
            return betweenValue;
        }

        public boolean isListValue() {
            return listValue;
        }

        public String getTypeHandler() {
            return typeHandler;
        }

        protected Criterion(String condition) {
            super();
            this.condition = condition;
            this.typeHandler = null;
            this.noValue = true;
        }

        protected Criterion(String condition, Object value, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.typeHandler = typeHandler;
            if (value instanceof List<?>) {
                this.listValue = true;
            } else {
                this.singleValue = true;
            }
        }

        protected Criterion(String condition, Object value) {
            this(condition, value, null);
        }

        protected Criterion(String condition, Object value, Object secondValue, String typeHandler) {
            super();
            this.condition = condition;
            this.value = value;
            this.secondValue = secondValue;
            this.typeHandler = typeHandler;
            this.betweenValue = true;
        }

        protected Criterion(String condition, Object value, Object secondValue) {
            this(condition, value, secondValue, null);
        }
    }
}